### ISSUE TITLE
Add type hints to content_tagging code in edx-platform

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#102]
Story: "As a developer, I want the content tagging code to have type hints so that it's more self-documenting and has fewer bugs"

Details:

1. Enforce typing and linting for the content_tagging app in edx-platform: https://github.com/openedx/edx-platform/tree/c75c706c6f6f4d46a06b6c98041f9a95ccf0ff3d/openedx/features/content_tagging

Criteria:

1. `content_tagging` is included in the mypy checks that run during CI tests
2. Add type hints to every function in the `content_tagging` app in edx-platform, including the tests (adding `-> None` as the return type is necessary if there are no other type hints in the parameter or return type, because otherwise mypy won't check the code in that function)

**Comment by pkulkark** [comment]
Here's the PR with the fix: https://github.com/openedx/edx-platform/pull/33484
