### ISSUE TITLE
[Tagging] Create Taxonomies List Page (in Course Authoring MFE)

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#104]
"As any user with access to Studio, I can see the new "Taxonomy" tab, which has the Taxonomy List Page. It displays any taxonomies that are enabled for my organization, as well as system-defined Taxonomies."

![Screenshot 2023-09-27 at 12 16 50 PM](https://github.com/openedx/modular-learning/assets/945577/6357640f-35e1-493b-b78a-893ae064bd8f)

Acceptance criteria:
1. Add a new link from Studio Home to this taxonomies list. (Alongside "Courses", "Libraries"). This should be hidden behind **a new feature flag** for now.
1. This should be part of [frontend-app-course-authoring](https://github.com/openedx/frontend-app-course-authoring).
1. As always, follow standard practices - Paragon, i18n, a11y, etc.
1. Taxonomies do not (yet) need to be clickable - no details available, no edit functionality (those come in subsequent stories)
1. For now, just show whatever taxonomies the API returns for the current user, without regard to whether they're system-defined or part of a specific org or disabled/enabled.
1. **UPDATED:** If a taxonomy is not "enabled" according to the API, hide it altogether.
1. **UPDATED:** If a taxonomy is "system defined" according to the API, display the "System-defined" badge:
    ![Screenshot 2023-10-11 at 2 26 58 PM](https://github.com/openedx/modular-learning/assets/945577/0c234249-a3e6-45a0-8a3a-5f5a5a53e8be)
1. **UPDATED:** The **three dots menu ⋮** will come in a later story - for now it can be omitted entirely.
1. If the description of the taxonomy is super-long, the text must be truncated with an ellipsis (see mockups).
1. The **header** is out of scope for now. Until it is available (until another team has implemented the new header, or we do so in a later phase #119), use **no header** and just a link back to the Studio home page.
    ![Screenshot 2023-09-27 at 12 17 12 PM](https://github.com/openedx/modular-learning/assets/945577/2ffd8b01-6675-4140-a4e0-868d48a20b59)
1. **UPDATED:** ~~Include a link to the documentation about Taxonomies. If available. If not, create a future story to track this TODO.~~ (don't worry about this for now)
2. Deploy the changes to [the tagging sandbox](https://github.com/openedx/modular-learning/issues/103#issuecomment-1730160020) and enable the feature flag for all users.

### Developer notes:

* Screenshots above are for convenience - [Figma](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP) is the most up-to-date source for mockups. The scale of UI elements seen in the screenshots above may be incorrect.
* If possible, I'd prefer that we [**Use TypeScript and React-Query**](https://openedx.atlassian.net/wiki/spaces/BPL/pages/3852632086/Typescript+and+React-Query+for+api+usage.) for accessing data from the Taxonomy API
* https://github.com/openedx/modular-learning/issues/107 should provide sample data, as there is no CRUD functionality in the UI yet.
* **Important**: The cards will be very similar to the code for cards from the Studio **Pages & Resources** page since they're almost identical in appearance. Re-use or copy code from that where it makes sense. The Taxonomy list should probably be a [**Paragon CardView**](https://paragon-openedx.netlify.app/components/datatable/#cardview-and-alternate-table-components) so we can get pagination and filtering in the future. (For now, hide its search/filter/page components and display all taxonomies at once.)
    ![Screenshot 2023-09-30 at 4 25 26 PM](https://github.com/openedx/modular-learning/assets/945577/53496c23-aa2a-4031-9eb0-1fefe1776d1a)

**Comment by bradenmacdonald** [comment]
@KristinAoki @arbrandes - do you think this new "Taxonomy" section of Studio should be part of [frontend-app-course-authoring](https://github.com/openedx/frontend-app-course-authoring) or be a new independent MFE?

@muselesscreator Is the "Typescript and React-Query" stuff far enough along for us to use it for data loading in this new MFE?

**Comment by arbrandes** [comment]
Given that there more than a few practical reasons for minimizing the number of MFEs (at least as they exist at time of writing), IMHO making this part of the Course Authoring repo is the way to go.

**Comment by KristinAoki** [comment]
Makes sense to me that it should be part of the course authoring MFE! Is this going to become part of the home page?

**Comment by bradenmacdonald** [comment]
@KristinAoki I'm not sure, it depends if 2U is refactoring the global Studio header to include the main tabs like "Courses", "LIbraries", etc. or not. Basically wherever you choose "Courses" or "Libraries" tabs, there will be a new third tab called "Taxonomies" that will open this new app. That may be either on the home page or the global header... in the UX mockups from @ali-hugo that you see above, it looks like they're in the global header, but in Studio today those are on the home page.

**Comment by bradenmacdonald** [comment]
@ali-hugo I thought I had removed that but I guess I missed it. Updated :)

**Comment by ali-hugo** [comment]
@bradenmacdonald @ChrisChV When testing out the Taxonomies page, I expected to be able to hover over the truncated card title, and see a tooltip displaying the full text (see mockup below).

![truncated card title](https://github.com/openedx/modular-learning/assets/88187719/1c22bb6f-7edf-4dc0-81ea-fc1e2d5e115e)

I'm not sure whether this has been [implemented in Paragon](https://paragon-openedx.netlify.app/components/truncate/#example-usage-in-card), but perhaps it should. What do you think?

**Comment by bradenmacdonald** [comment]
^ We will fix the above shortly in FAL-3537.
