### ISSUE TITLE
[Tagging] Indicate when a taxonomy is used by multiple organizations

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#109]
Follow up to #108. Merged into #117.

~~1. Indicate when a taxonomy is used by multiple organizations, as shown.~~

![Frame 5345](https://github.com/openedx/modular-learning/assets/88187719/d3183222-e57b-4e02-b559-0e0e1da1e8a1)

~~2. Users can select the 3-dot menu, then choose "manage organizations":~~
~~3. A modal appears showing which organizations have been assigned, as well as allowing the user to assign or unassign:~~

![Frame 5347](https://github.com/openedx/modular-learning/assets/88187719/2f4f00f6-61d4-4b55-866e-a473330e23c5)

**Comment by ali-hugo** [comment]
@bradenmacdonald The UX for this has changed quite a bit:

- Users can no hover over the label to view the assigned organizations; they need to select the 3-dot menu, then choose "manage organizations":

![Frame 5345](https://github.com/openedx/modular-learning/assets/88187719/d3183222-e57b-4e02-b559-0e0e1da1e8a1)

- A modal appears showing which organizations have been assigned, as well as allowing the user to assign or unassign: 

![Frame 5347](https://github.com/openedx/modular-learning/assets/88187719/2f4f00f6-61d4-4b55-866e-a473330e23c5)

**Comment by bradenmacdonald** [comment]
@ali-hugo  In that case, we don't need this story - I'll merge it into #117.
