### ISSUE TITLE
[Tagging] Add "Expand All" button to Taxonomy View

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#112]
1. When viewing or editing a taxonomy with hierarchical tags, the new "Expand All" button should load and display all children/grandchildren of the currently visible page of root tags.
2. If all the children/grandchildren are visible, the button should change to "Collapse all"
3. If the Taxonomy has more than **TBD: X** tags, the "Expand all" functionality can be disabled, as it would require loading too much data.

![Screenshot 2023-09-19 at 5 29 52 PM](https://github.com/openedx/modular-learning/assets/945577/45cf42c0-27e4-4a81-8164-bf6bc734226e)

**Comment by bradenmacdonald** [comment]
@ali-hugo do you think we can just leave this as-is for MVP? I know the Figma are more wireframes than finalized UX, so I'm thinking if the "Expand All" is basically present and working, it's not worth spending much time on this now until after we've had a round of user testing and feedback.

So @pomegranited  I'm thinking let's just call this done for now, but wait to see what Ali says.

We can put any follow-ups into https://github.com/openedx/modular-learning/issues/155 which is probably a better idea anyways since we'll have to make sure we account for things like dragging tags around, multi-select of tags, keyword filtering, etc. I _think_ we can still do all of that using this same <DataTable> as a basis but things could change.

Here's how it looks now:

![Screenshot 2023-11-23 at 11 59 05 AM](https://github.com/openedx/modular-learning/assets/945577/28c807f5-029b-44d9-88d0-ca771002ed37)

![Screenshot 2023-11-23 at 11 59 25 AM](https://github.com/openedx/modular-learning/assets/945577/4c25acfc-d74c-4c42-9a42-0a9ef76c66cb)

**Comment by pomegranited** [comment]
FYI @ChrisChV ^

**Comment by ali-hugo** [comment]
> @ali-hugo do you think we can just leave this as-is for MVP?

@bradenmacdonald @pomegranited @chrischv Yes, I think this is ok to leave as is for MVP. The only thing I think might be worth tweaking (but only if it's a _quick_ change), would be to lose the "child tags" column, and rather include a little gray number next to the parent tags (just like the child tags have). But if that's not a simple fix, I think @bradenmacdonald's right when he says we should leave this as is until we have some user feedback. 👍
