### ISSUE TITLE
[Tagging] Display a unit's tags in the tag drawer

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#118]
"As a content author, I can see what tags have been applied to a unit in my course (from the course outline page)"

### Acceptance Criteria

1. From the course outline page:
    a. There is a new "Manage Tags" menu item available on each **unit** (only units, not subsections etc.). Clicking it will open the new tag drawer.
        ![Screenshot 2023-09-21 at 12 24 45 PM](https://github.com/openedx/modular-learning/assets/945577/c935d448-e953-4456-97e0-225fef436362)
    b. For units which have tags, the number of tags that they have appears next to this tag icon. Clicking the number/icon will also open the tag drawer.
       ![Screenshot 2023-09-21 at 2 44 49 PM](https://github.com/openedx/modular-learning/assets/945577/a04a8c0a-611b-468f-92e4-8b229e3414be)
    c. Both the "Manage Tags" and the tags count should **only appear to users who have a feature flag enabled** (same feature flag as #104) 
3. The tag drawer appears on the right, and displays the tags that are applied to the unit, separated by Taxonomy.
    ![Screenshot 2023-09-30 at 4 36 40 PM](https://github.com/openedx/modular-learning/assets/945577/316fc6aa-6bc0-415e-b37d-050acf246e50)

    ![Screenshot 2023-09-21 at 12 30 39 PM](https://github.com/openedx/modular-learning/assets/945577/d30a0120-55dc-4bc6-9f8b-ee16b68e91b2)
4. Tags are displayed using these criteria:
    ![Screenshot 2023-09-21 at 12 31 10 PM](https://github.com/openedx/modular-learning/assets/945577/f825340a-a08d-4cfd-8b71-97699bd85a1e)
5. A scrollbar appears for long lists (see Figma)
5. For each taxonomy there is a count of tags displayed (see mockups)
6. For this story, we **do not implement any editing** (no adding nor deleting tags)
7. Everything must be fully keyboard accessible. Checking what tags are applied using a screen reader should be easy and make sense. Pressing ESC should close the drawer.
8. The tag drawer must be implemented in React.

### Developer Notes
* **The drawer should probably be built in frontend-app-course-authoring and use an iframe to display it in the "old" course authoring experience.** If you want to take any other approach please clear it with @bradenmacdonald first.
* Screenshots above are for convenience - [Figma](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP) is the most up-to-date source for mockups. The scale of UI elements seen in the screenshots above may be incorrect.
* Because of https://github.com/openedx/modular-learning/issues/99 note that the list of tags on each unit is never paginated. This should simplify things a little bit.

**Comment by ali-hugo** [comment]
Linking to the [Figma conversation](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa?node-id=1:6226&mode=design#563357597) for easy reference when the below decision has been made:

> (TBD: what exactly appears on the left? Asked on Figma)

**Comment by bradenmacdonald** [comment]
Note: the above decision has been made :)

**Comment by ali-hugo** [comment]
@yusuf-musleh @bradenmacdonald Everything seems to be working quite well in the sandbox. I just have a few comments:

- Please change the order of the items in the unit menu to:
  - Configure
  - Manage tags
  - Copy to clipboard
  - Duplicate
  - Delete
- The number next to the taxonomy name in the tag drawer should include all implicit and explicit tags. It only seems to include a count of explicit tags at the moment
- Remove the hover effect from the tags. Only display a hover effect for the X's next to explicit tags (since this is the only part of the tag that is currently clickable)

P.s. I will be creating a separate issue with a few additional styling requests, but I will probably wait until the first round of testing has been completed so that I can account for user feedback there too.

**Comment by yusuf-musleh** [comment]
@ali-hugo Thanks for the feedback, glad to hear things are working well. I will include the suggested changes along with other feedback I get on https://github.com/openedx/frontend-app-course-authoring/pull/704 once its reviewed. Though the first point (changing the order of items in unit menu would be a different PR in the edx-platform repo)

**Comment by bradenmacdonald** [comment]
For the order of the menu, I will include it in FAL-3537.

**Comment by ali-hugo** [comment]
@yusuf-musleh Thank you! This looks great :)
