### ISSUE TITLE
[Tagging] View/edit tags for a library component

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#121]
"As a Content Author, I can add/delete tags to content components (text blocks, video blocks, problem blocks) in a v2 Library."

"As a Content author, I can view tags that have already been added to content components in a v2 Library."

"As a Content Author, I expect that the experience to view, add and delete tags to content components mirrors the UI and experience when I view, add and delete tags to component xblocks on a Unit Page in a course."

### Acceptance Criteria

1. From [**the new libraries MFE**](https://github.com/openedx/frontend-app-library-authoring), I can select "Manage Tags" for any library component
    ![Screenshot 2023-09-21 at 3 04 54 PM](https://github.com/openedx/modular-learning/assets/945577/cbe5ef07-1a1f-47e6-95cf-db4c76a74053)

In the library authoring MFE, it would look more like this:
![Screenshot 2023-12-19 at 11 59 03 AM](https://github.com/openedx/modular-learning/assets/945577/4741dbe7-85f8-4772-b98c-236976e56372)

2. The existing "Delete" icon should be moved to become a "Delete" item in the three dots menu.

2. Clicking "Manage Tags" opens the tagging drawer with the same tag viewing and editing functionality as units and course components have.

3. I can add/remove tags using the tagging drawer.

4. Components that have at least one tag display the total tag count as a clickable button, just like on the unit page:

Note: this is just showing where the "tag count button" goes in the new MFE. This is not how it should look:

![Screenshot 2023-12-19 at 11 57 23 AM](https://github.com/openedx/modular-learning/assets/945577/9abcc1e7-95bb-46dd-815f-d7b3e7f5bfd3)

It should look something more like this, but in the style of the new MFE:

![Screenshot 2023-12-19 at 11 56 25 AM](https://github.com/openedx/modular-learning/assets/945577/27cef93f-668d-4868-a41d-9f9fa60305c7)

5. For now this can just open the tag drawer in an iframe, but based on #164 we'll find a better way to integrate it.

6. This is all for v2 libraries only; no need to support v1. The library URL/ID should start with `lib:`, which indicates a v2 library.

**Comment by bradenmacdonald** [comment]
@jmakowski1123 @ali-hugo please review the UI here, and if you can provide a mockup of exactly how you'd like it to look, it would be super helpful.

**Comment by bradenmacdonald** [comment]
@jmakowski1123 @ali-hugo Scratch that - please look at https://github.com/openedx/frontend-app-library-authoring/pull/400

**Comment by ali-hugo** [comment]
@bradenmacdonald [#400](https://github.com/openedx/frontend-app-library-authoring/pull/400) looks good! My only feedback would be that the pencil icon should match the "icon + edit" element used elsewhere in Studio (see screenshot below), but I think this might fall outside of the ticket scope. I thought I'd mention it in case it doesn't.

![Screenshot 2024-01-08 at 11 33 09](https://github.com/openedx/modular-learning/assets/88187719/cd32810e-db55-4ac2-a963-063161bd93bc)

**Comment by bradenmacdonald** [comment]
@ali-hugo That's outside the scope here, as 2U already settled on that pencil icon for the new MFE. If you'd like to change it, could you discuss it with Jon?

**Comment by ali-hugo** [comment]
@bradenmacdonald 

> @jmakowski1123 @ali-hugo please review the UI here, and if you can provide a mockup of exactly how you'd like it to look, it would be super helpful.

@jmakowski1123 and I chatted briefly about the Library Authoring MFE. It should be up soon 🤞 . Would it suit you for us to wait for it to go live before weighing in on any related design decisions?

**Comment by bradenmacdonald** [comment]
Yep that's fine. We have solved the issues with our sandbox today, so it should be working by tomorrow, including the libraries MFE.

**Comment by bradenmacdonald** [comment]
@ali-hugo Yep that's fine. We have solved the issues with our sandbox today, so it should be working by tomorrow, including the libraries MFE.
