### ISSUE TITLE
[Tagging] Edit a content item's tags from the tag drawer

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#122]
"As a Content Author, I can add/delete tags to content components (course blocks, course units, and library blocks)."

Builds on the read-only tag drawer created in https://github.com/openedx/modular-learning/issues/118 to make it editable. Also see #120 and #121 which provide different ways of opening the tag drawer.

### Acceptance criteria

1. Check permissions. This new edit functionality should only appear in the tag drawer if the user has permission to edit the unit/component/library-component in question. Otherwise, the previous read-only view should be used.
1. Display an "x" for explicit tags in the tag drawer. Clicking the "x" will remove the tag from the content item.
2. Removing an explicit child that is the only child of its implicit parent will remove the implicit parent too (and grandparent etc.)
3. New tags can be added, using the filterable tags list box (**filtering/searching** is included in scope for this ticket):
    ![Screenshot 2023-09-21 at 3 13 26 PM](https://github.com/openedx/modular-learning/assets/945577/f36f3a07-866b-4c5e-a16f-d426e8f79d4c)
4. Tag selection:
    - Selecting the checkbox of a parent tag does not select the tags it contains
    - Selecting a nested tag automatically assigns an indeterminate state to the parent checkbox
    - When users click on a nested tag, it becomes the explicit tag and its parent tags are included as implicit tags with a checkbox in a lighter shade of gray. Users cannot check/uncheck implicit tags
    - When users uncheck a nested, explicit tag, its implicit parent tags automatically become unchecked
    - The most granular tag in the hierarchy becomes the explicit tag with all its parent tags becoming implicit
5. Tag interaction: To select/deselect an item, select either the checkbox or the tag name. To expand parent items, select the dropdown arrow or any empty area on the row
6. Everything is fully accessible and in particular is easy to operate with a keyboard.

### Developer Notes
* Toast notifications will come later in https://github.com/openedx/modular-learning/issues/123
* Screenshots above are for convenience - Figma is the most up-to-date source for mockups. The scale of UI elements seen in the screenshots above may be incorrect.

**Comment by ChrisChV** [comment]
@bradenmacdonald Is searching for tags within the scope of this task?

**Comment by bradenmacdonald** [comment]
@ChrisChV Yes, I think so. Why? Let me know if you think we should split it out.

**Comment by ChrisChV** [comment]
> Let me know if you think we should split it out.

@bradenmacdonald No, I think this is fine on this task. Only it would have to be specified in the description. There are several separate functionalities and since it was not specified, my first impression was that it was separated into another task.

**Comment by bradenmacdonald** [comment]
This has now merged, except for the ability to search/filter the tags which is still WIP.

**Comment by bradenmacdonald** [comment]
Searching tags has now merged!
