### ISSUE TITLE
[Tagging] Refined UX: Update a taxonomy by downloading and uploading

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#126]
"As a global staff user (instance-level super-admin), I can update a taxonomy by downloading, editing, and re-importing it."

This improves the UX and workflow of the basic functionality implemented in https://github.com/openedx/modular-learning/issues/140.

### Acceptance Criteria

1. From the Taxonomies List Page, global staff will see the "Re-import" menu option from https://github.com/openedx/modular-learning/issues/140
2. Likewise, from the Taxonomy Detail Page, global staff can access the same option:
    <img width="329" alt="Screenshot 2023-10-12 at 09 47 52" src="https://github.com/openedx/modular-learning/assets/88187719/6e37880c-9194-43b8-be99-e2133b8db490">
2. Users who select that menu command will then see this dialog and can choose to download the taxonomy as either CSV or JSON:
    ![Screenshot 2023-09-25 at 11 03 12 AM](https://github.com/openedx/modular-learning/assets/945577/408bf1f9-d110-4405-807e-4df776002e45)
4. Users will then see this:
    ![Screenshot 2023-09-22 at 9 56 49 AM](https://github.com/openedx/modular-learning/assets/945577/24711d9b-e7ee-4346-9b39-1515f81b802c)
5. If they click "Import" a file chooser will open, which allows only .csv or .json files as already implemented in #140.
6. The import will be analyzed and the changes shown to the user (note: handle a long list using a scroll bar in the modal):
    ![Screenshot 2023-09-22 at 9 58 31 AM](https://github.com/openedx/modular-learning/assets/945577/610a5a4d-38e3-4b71-a9c6-fc7d0a98f11b)
7. A second confirmation is shown to the user if they choose to proceed:
    ![Screenshot 2023-09-22 at 9 59 30 AM](https://github.com/openedx/modular-learning/assets/945577/928205ea-109e-4059-9b16-63e794880d85)
8. If the user confirms, the taxonomy is updated and a toast is shown.
    ![Screenshot 2023-09-22 at 9 59 55 AM](https://github.com/openedx/modular-learning/assets/945577/603fb8c3-2f91-45aa-87cd-75e597a2bae6)
9. If errors occur, they will be shown at the top of the page as seen in the Import workflow mockups.
    ![Screenshot 2023-10-06 at 10 02 56 AM](https://github.com/openedx/modular-learning/assets/945577/53ead8bf-0a3b-4a27-b612-0e92a8db70f8)

### Developer Notes
* Screenshots above are for convenience - [Figma](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP) is the most up-to-date source for mockups. The scale of UI elements seen in the screenshots above may be incorrect.
* As always, make sure the whole process can be done using only a keyboard.

**Comment by rpenido** [comment]
> 4\. Users will then see this:
>         ![Screenshot 2023-09-22 at 9 56 49 AM](https://private-user-images.githubusercontent.com/945577/270004730-24711d9b-e7ee-4346-9b39-1515f81b802c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzU5MTcsIm5iZiI6MTcwMTI3NTYxNywicGF0aCI6Ii85NDU1NzcvMjcwMDA0NzMwLTI0NzExZDliLWU3ZWUtNDM0Ni05YjM5LTE1MTVmODFiODAyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQxNjMzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzJhYmVjYjk3NDM5YWQ3MjY0MDcwOGEwZWMyZTg0MDVmMDA4Mjc5ZGZlYmRmNjczNGI5ZTY3N2U4NTlmNjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VxtTyaJTCn1Xp1yM3Ics9EAUnlXvh2aYZUuivslOUO8)

Hi @ali-hugo!
Is it okay to add a [Dropzone](https://paragon-openedx.netlify.app/components/dropzone/) in this dialog instead of calling an open file dialog? I think it will be cleaner to implement and have a nicer look. Like this:

![image](https://github.com/openedx/modular-learning/assets/849463/788ebd75-3032-4786-9e22-50dddc586e99)

**Comment by rpenido** [comment]
> @bradenmacdonald We have changed the terminology in the UI from "update taxonomy" to "re-import":
> <img alt="Screenshot 2023-10-12 at 09 47 52" width="329" src="https://private-user-images.githubusercontent.com/88187719/274523816-6e37880c-9194-43b8-be99-e2133b8db490.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzU5MTcsIm5iZiI6MTcwMTI3NTYxNywicGF0aCI6Ii84ODE4NzcxOS8yNzQ1MjM4MTYtNmUzNzg4MGMtOTE5NC00M2I4LWJlOTktZTIxMzNiOGRiNDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE2MzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMjAwNWE0ZjA5NjE5ZGE1MzJjZDIyZDU3Y2E4MjNjYjdiZDRjYjJiNmM2ODljODdkOWUxMWQ3MzM4ZGJhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yOH5G_QQd_laUo4C_rJBjCTwXmfqqWK9BXCLjvXQX68"> <img alt="Screenshot 2023-10-12 at 09 48 48" width="581" src="https://private-user-images.githubusercontent.com/88187719/274523860-878f88af-18d9-432c-b2f8-15ad1fd56510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzU5MTcsIm5iZiI6MTcwMTI3NTYxNywicGF0aCI6Ii84ODE4NzcxOS8yNzQ1MjM4NjAtODc4Zjg4YWYtMThkOS00MzJjLWIyZjgtMTVhZDFmZDU2NTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE2MzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOThmN2Y1NTVhYWQwMTM5N2QzMWI3YzMxZWQwN2ZlZDcwMGRmZGRiZWJiZTMzNWVhNzQ2OTU4Mzc4ZjA2OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b3fkes3Jz6-HiOa3BQeXEOSAWuxT419JNGVsl_Qzcpg">
> 
> (Not directly related to this issue, but might be worth mentioning: we added the "edit details" menu item to the dropdown accessed from the "actions" button on the Taxonomy Detail Page.)

Is it safe to say that these menus will stay the same from now? We started with two different menus. As part of this task, I made a minor refactor to merge these menus and avoid code duplication. Let me know if I'm on the right path!

**Comment by pomegranited** [comment]
@rpenido
> Is it okay to add a [Dropzone](https://paragon-openedx.netlify.app/components/dropzone/) in this dialog instead of calling an open file dialog? I think it will be cleaner to implement and have a nicer look.

That's the UI @ali-hugo wanted to begin with, so I'm sure it will be fine :)

> Is it safe to say that these menus will stay the same from now?

Yes, they should stay the same.

**Comment by ali-hugo** [comment]
@rpenido The dropzone looks good - thanks! 

Could you make a few small text changes please? See the text in the blue blocks below. Don't worry about the one about the maximum file size if it's not relevant.

![Dropzone](https://github.com/openedx/modular-learning/assets/88187719/d518e1e6-b813-479c-bf1c-01a5ff6a84ee)

Thanks for the ping! Let me know if you have any questions.

**Comment by rpenido** [comment]
Hi @ali-hugo!

I made a small video of the implementation as it is now, and I would like your feedback!

https://github.com/openedx/modular-learning/assets/849463/9b07d131-ee70-4aa9-8e41-57ba0ea2cb19

I used a [Stepper](https://paragon-openedx.netlify.app/components/stepper/) and added the `Previous` buttons.

I highlighted below the major changes:

## Verify plan ##
### Design ###
![Screenshot 2023-09-22 at 9 58 31 AM](https://private-user-images.githubusercontent.com/945577/270005066-610a5a4d-38e3-4b71-a9c6-fc7d0a98f11b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4OTI3NjEsIm5iZiI6MTcwMTg5MjQ2MSwicGF0aCI6Ii85NDU1NzcvMjcwMDA1MDY2LTYxMGE1YTRkLTM4ZTMtNGI3MS1hOWM2LWZjN2QwYTk4ZjExYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxOTU0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzY5YThjMzRjNDQyNjFmMTViNmE3NGI4YmQ2ZmE1NGUwNWRiZWU1YmIxZWUxNzczMjgxYTM4MzA0ZWFiOGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DK2BjCUdf3-_LJK6kL3NtFxlynKr7JgNdZtyyTyqllg)
### Implementation ###
![image](https://github.com/openedx/modular-learning/assets/849463/4d6de434-5929-40e3-adc1-f6ded3913b9e)

In this screen, I didn't format the import plan. The backend saves the plan as a text log. I just made some minor adjustments to show it as a list. Some text adjustments are possible, but formatting each action as in the image would take some effort. Is the current approach enough for the MVP?

## Confirm ##
### Design ###
![Screenshot 2023-09-22 at 9 59 30 AM](https://private-user-images.githubusercontent.com/945577/270005283-928205ea-109e-4059-9b16-63e794880d85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4OTI3NjEsIm5iZiI6MTcwMTg5MjQ2MSwicGF0aCI6Ii85NDU1NzcvMjcwMDA1MjgzLTkyODIwNWVhLTEwOWUtNDA1OS05YjE2LTYzZTc5NDg4MGQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxOTU0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWZlNjUyZGYyYzJhNDUzODc1NWQ3NTllNDQ5ZTAwYjU3ODJhYjIzOTUxMmY2ZDFlMWQyODUxNmRkZWVjYzU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v7owSXY6yAotFORj7-KttigKrWqrqsoVz0nRqkwYz0c)
### Implementation ###
![image](https://github.com/openedx/modular-learning/assets/849463/25300b28-d259-45a6-b6c7-46aea23530b1)

In this screen, we don't have the actual number of the tags affected by the import, but the action count instead (we could have more than one action per Tag). I reworded the text to reflect that. Could you validate it?

---

If you see something that need to be changed (or need more screenshots) please let me know!

**Comment by ali-hugo** [comment]
@rpenido Thanks for the video! This is looking good :) See my feedback below:

Sorry, I see this is not clear in the designs, but instead of seeing a screen like the one on the left below, I was expecting to see something like on the right iIt's not important to change at the moment, so please only make the update if it's quick and easy.)
![Screenshot 2023-12-07 at 10 51 48](https://github.com/openedx/modular-learning/assets/88187719/bc64f454-e55a-4922-ab90-0bc8a1dc4aca)

---

I think what you've done for the list in the screenshot below is perfect! Please just remove the warning from this screen - I think it's overkill to show it twice. Also, please change the button text to "continue":

![Screenshot 2023-12-07 at 11 10 02](https://github.com/openedx/modular-learning/assets/88187719/dfc0640f-8a3e-4b29-825b-96ab8e4f3a8f)

---

Please change the colour of the red button in the image below to match the rest of the buttons. Also, I've made one small tweak to the text you wrote:

_Warning! You are about to make 14 changes to the existing taxonomy. Any tags applied to course content will be updated or removed. This cannot be undone. 

Are you sure you want to continue importing this file?_

![288536043-25300b28-d259-45a6-b6c7-46aea23530b1](https://github.com/openedx/modular-learning/assets/88187719/7662789b-9157-4491-9a1f-09afe62e9838)

**Comment by bradenmacdonald** [comment]
@rpenido @ali-hugo Nice work, it's looking great!
