### ISSUE TITLE
[Tagging] Delete a taxonomy

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#127]
"As a global staff user (instance-level super admin), I can delete a taxonomy."

### Acceptance Criteria

1. Global staff users will see this "Delete" menu for non-system taxonomies on the Taxonomy List Page:
    ![Screenshot 2023-09-22 at 10 11 11 AM](https://github.com/openedx/modular-learning/assets/945577/3f24fcd4-2562-49c3-a14a-4cd56aef0119)
2. And the same option can be accessed from the Taxonomy Detail Page:
    ![Screenshot 2023-09-22 at 10 16 03 AM](https://github.com/openedx/modular-learning/assets/945577/c579db0d-4e0e-4e12-a9b9-1e35ff0ea878)
2. Clicking that option will reveal this confirmation dialog:
    ![Screenshot 2023-09-22 at 10 11 25 AM](https://github.com/openedx/modular-learning/assets/945577/573e99a4-a19c-47ea-870a-74c140d1edac)
4. The "Delete" button will be disabled until/unless users type "DELETE" in the field.
5. Once users click "Delete", the taxonomy will be deleted and a toast shown. If they were on the Taxonomy Detail Page, they are redirected to the Taxonomy List Page.
    ![Screenshot 2023-09-22 at 10 12 21 AM](https://github.com/openedx/modular-learning/assets/945577/57bd1edc-5968-4402-ada4-df565e869764)
6. Implementing "Undo" as seen above is *not* required (out of scope). That may come later in #135.

### Developer Notes
* Screenshots above are for convenience - Figma is the most up-to-date source for mockups. The scale of UI elements seen in the screenshots above may be incorrect.
* As always, make sure the whole process can be done using only a keyboard.

**Comment by ChrisChV** [comment]
> Once users click "Delete", the taxonomy will be deleted and a toast shown.

@bradenmacdonald The "Undo" functionality of the toast will be implemented in https://github.com/openedx/modular-learning/issues/135?

**Comment by bradenmacdonald** [comment]
@ChrisChV  Yes but that particular story has been postponed, so I'm not sure if/when we'll implement undo.

In any case, you do not need to implement undo as part of this story.
