### ISSUE TITLE
[Tagging] CRUD API for editing tags in a taxonomy

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#136]
"As a user, I want to be able to make basic edits to a taxonomy from the UI"

### Acceptance Criteria

1. A python and REST API allow adding a tag to a taxonomy.
2. A python and REST API allow renaming a tag.
    * changes to the tag `value` should propagate to `ObjectTag`s ?
3. A python and REST API allow deleting an individual tag. If it has children, by default the delete will fail, but if the with_subtags option is specified, all subtags will be deleted as well.
4. A python and REST API allow bulk-deleting of tags. For simplicity this can be combined with (3) into a single "delete tags" API. The same criteria for handling sub-tags as 3 applies.
5. Attempting to bulk-deleting tags from more than one taxonomy should result in an error message. Bulk delete only works within a single taxonomy at a time.
6. When tags are deleted, the ObjectTags get their tag set to NULL and will be hidden, but the ObjectTags are preserved in the database and can later be re-synced if a tag with the same name is re-created. (This is already implemented.)
7. The REST API must respect the permissions defined in #129.

This API will be used for #132, #131, #130.

**Comment by pomegranited** [comment]
> 5. Attempting to bulk-deleting tags from more than one taxonomy should result in an error message. Bulk delete only works within a single taxonomy at a time.

@bradenmacdonald How important is it to return an error in this case? The current [proposed implementation](https://github.com/openedx/openedx-learning/pull/96/files#diff-7ffb9100f9426c81c59e88e9beceb9e3a8089da152d1d605b7de97990e6f0d50R427) only deletes the tags in a single taxonomy, and it ignores (but does not error for) tags found in other taxonomies.
