### ISSUE TITLE
[Tagging] Create Taxonomy Templates

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#137]
"As an org-level admin, I can see templates that show me how to format taxonomy data in CSV or JSON format, so I can create and upload custom taxonomies."

### Acceptance Criteria

1. Create templates in both CSV and JSON that demonstrate how to represent hierarchical tag data.
2. The template files themselves should contain instructions for how to use them.
3. If a user immediately imported the Template files without making changes, they should import successfully (contain no errors).

Later, these templates will be used for #114.

**Comment by pomegranited** [comment]
@bradenmacdonald 

https://github.com/openedx/modular-learning/issues/114 says:

> * This task does not have to involve the backend at all; the templates could be part of the frontend unless there is a good reason to generate them on the backend.

I'm pretty sure it's easy enough to serve these template files from the [frontend-app-course-authoring](https://github.com/openedx/frontend-app-course-authoring), e.g. [like this](https://stackoverflow.com/a/50376496).

But if we need tests to verify that the templates can always be imported without error, it's easier to store and serve them from the backend.

Which do you prefer?

**Comment by bradenmacdonald** [comment]
@pomegranited  I didn't think about that. It makes sense to keep them on the backend for that reason! As long as there's a relatively simple way to download them from the frontend.

**Comment by pomegranited** [comment]
@bradenmacdonald Yep, the frontend can just provide a button/link to the backend's download URL.

I will add that endpoint as part of this ticket too.

**Comment by bradenmacdonald** [comment]
The templates can be seen as `template.csv` and `template.json` in https://github.com/openedx/openedx-learning/tree/main/openedx_tagging/core/tagging/import_export - FYI @e0d
