### ISSUE TITLE
[Tagging] "Bare Bones" Taxonomy Detail Page

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#138]
"As a content author, I can view an enabled taxonomy's metadata and tags."

### Acceptance Criteria
1. From the Taxonomies List Page #104, when a user clicks anywhere on the taxonomy card that's not one of the menus/icons, they will be taken to a stripped-down version of the Taxonomy Detail Page. Here's what the full version will look like:
![Screenshot 2023-09-19 at 5 06 25 PM](https://github.com/openedx/modular-learning/assets/945577/3d12ee52-6506-4263-87c5-7dffe8034598)
2. For the bare-bones version, just display all tags, expanded. No collapsing/expanding sections. If not all tags can be loaded at once, use "load more" links where necessary or some other simple solution.
4. The sidebar will display the taxonomy's title and description. Copyright info is not implemented so will come later.
7. Add an Actions button with "Export taxonomy ~~as JSON~~" ~~and "Export Taxonomy as CSV"~~ - same functionality as #105 but it can now be accessed from this page too. No need to implement other actions - those are different stories.
    ![Screenshot 2023-09-22 at 10 34 18 AM](https://github.com/openedx/modular-learning/assets/945577/f3ad6744-a3f8-45e8-b885-d90092f28f8c)
7. Do not implement Keyword filtering for now - that will come in https://github.com/openedx/modular-learning/issues/128
8. Do not implement "Expand All" for now - that will come in https://github.com/openedx/modular-learning/issues/112

### Developer Notes

* The same view will be re-used as the "Edit Taxonomy" view, so design with that in mind.
* Screenshots above are for convenience - [Figma](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP) is the most up-to-date source for mockups. The scale of UI elements seen in the screenshots above may be incorrect.
* We may or may not keep the pagination tweak in-scope for this MVP, but in any case it's a separate ticket - see https://github.com/openedx/modular-learning/issues/111
* To make the taxonomy card clickable while preserving a11y, put a "view taxonomy details" link inside the card, make its inner text visible only to screen readers, and use [`.stretched-link`](https://medium.com/@pratva.bsta/nested-links-in-cards-a-solution-for-clickability-issues-98b063cb347c) (bootstrap class) to make the link cover the whole card.

**Comment by ali-hugo** [comment]
@rpenido  Thanks for your work on this! I've just taken a look at this on the sandbox and have a couple of notes:

- Please change the title of the "Value" column to "Tag name"
- I have a question about the zebra stripes on the table. When a row is expanded, is it possible to have the background of the expanded section match the background of the parent tag? So in the screenshot below, the gray background behind the tags "Cognitive Abilities", "Communication Abilities", "Verbal Ability" etc would be white to match the background of the "Abilities" parent tag. That way, it's more clear that those sections are related.

<img width="1075" alt="Screenshot 2023-11-28 at 14 19 36" src="https://github.com/openedx/modular-learning/assets/88187719/42d695fe-8fb2-41a8-aac8-6fccbbe3df07">

CC: @bradenmacdonald

**Comment by bradenmacdonald** [comment]
@ali-hugo The first one is an easy fix. For the second one, we're just using the existing "expand" functionality built into Paragon's DataTable, and it doesn't let you control the stripe colors as far as I can see. So it's something we can fix in #155 along with any other major changes, but I don't think we should spend the time on it now before we're confident about what other changes will be needed. I'll add this into #155.

**Comment by rpenido** [comment]
Hi @ali-hugo! Thank you for the input! Let us know if you find more improvements!
