### ISSUE TITLE
Add validation check for mismatched Content Group settings in Components

### ISSUE THREAD

**Issue by ormsbee** [openedx/modular-learning#14]

**Comment by bradenmacdonald** [comment]
@jmakowski1123 @ormsbee @ali-hugo 

I think this already exists in the platform.

Here's what happens now. Note that this XBlock is restricted to a particular content group. If I copy it:

![Screenshot 2023-05-31 at 6 12 57 PM](https://github.com/openedx/modular-learning/assets/945577/274331ff-7779-45eb-8fdc-fb86937c5042)

Then paste it into a different course, I get this warning:

![Screenshot 2023-05-31 at 6 14 19 PM](https://github.com/openedx/modular-learning/assets/945577/e79c1c69-8e35-4b5c-9359-605e34cc15c2)

This seems to be compatible with the technical approach doc which says: "For the initial MVP, allow incompatible items to be pasted, and surface the errors in the Studio UI."

So: is this behavior sufficient, or do we want something different?

**Comment by ormsbee** [comment]
@bradenmacdonald: yeah, I think the existing UI is sufficient–I just wasn't aware of it when I wrote this. I'm closing this for now–anyone should feel free to re-open it if you think it needs further discussion.
