### ISSUE TITLE
[Tagging] Show tag count for each tagged component on the Unit Page

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#158]
On the unit page, when a component (XBlock) has at least 1 tag, the tag count button should appear, just like for units on the course outline page. Clicking it should open the tag drawer.

![Screenshot 2023-12-01 at 10 18 00 AM](https://github.com/openedx/modular-learning/assets/945577/26506427-c477-4617-8a27-dace101957b4)

Should have the same button as seen on units on the outline:

![Screenshot 2023-12-01 at 10 19 19 AM](https://github.com/openedx/modular-learning/assets/945577/c72f4b0a-9a41-43d6-869d-868b543864c4)

### Acceptance criteria
1. Components with no tags do not display the button
1. Components with 1+ tag(s) do display the button
1. The tag count for all the components on the page is loaded at once. ([use `,` to separate component IDs with this API](https://github.com/openedx/openedx-learning/blob/06f4f5476f2dc70ee4664960d8f6988b3f83e505/openedx_tagging/core/tagging/rest_api/v1/views.py#L492-L498))
1. Update the wiki page at https://openedx.atlassian.net/wiki/spaces/COMM/pages/3866689562/New+Additions+to+the+Course+Unit+Page to mention this new feature.

**Comment by bradenmacdonald** [comment]
FYI @jmakowski1123 @ali-hugo

**Comment by bradenmacdonald** [comment]
@jmakowski1123 @ali-hugo Here's what it would look like if we basically copy the code from the outline onto the unit page. If this looks good, we'll go with it; if you want something that looks different, a mock would be helpful.

![Screenshot 2023-12-01 at 11 56 00 AM](https://github.com/openedx/modular-learning/assets/945577/a334ac76-4df8-4083-ad80-12cdb53152bc)

![Screenshot 2023-12-01 at 11 56 14 AM](https://github.com/openedx/modular-learning/assets/945577/e58089ff-30eb-454d-a697-9a3f73446a0d)

**Comment by ali-hugo** [comment]
@bradenmacdonald What you have in the screenshot above is perfect. I've updated the design files to match.
