### ISSUE TITLE
Copy/Paste associated static assets

### ISSUE THREAD

**Issue by ormsbee** [openedx/modular-learning#16]
* This must be implemented in a way that is pluggable.
* A bit of prior art from LabXchange work might be useful as a starting point, e.g. see the [OLX REST API](https://github.com/openedx/edx-platform/tree/master/openedx/core/djangoapps/olx_rest_api) which provides a list of the static assets used by the given components/OLX.
* Must be smart enough to detect when an asset already exists in the destination location (matching filename).
* Should display in the Paste preview.

Edge cases:

* If a linked asset in the Source and Destination courses have the same name and data, there is no need to copy the asset.
* If a linked asset in the Source course has the same name as a _different_ asset in the Destination course (identified by hash), we should copy over the asset but rename it to avoid overwriting.
* If the `python_lib.zip` is not the same between the Source and Destination courses, a warning should be surfaced to the user.
* We make no effort to copy `python_lib.zip` at this time.

**Comment by bradenmacdonald** [comment]
For what it's worth, the [`xblock_serializer`](https://github.com/openedx/edx-platform/tree/master/openedx/core/lib/xblock_serializer) code that I made (and that is already the basis of the copy/paste feature) already has a pretty good implementation of listing the static assets used by a block, and retrieving them via API. We just need to store them in the "staged content" area and import them into the course on paste.

**Comment by bradenmacdonald** [comment]
Also, show this notification at the top of the Studio page (see Figma):

![Screenshot 2023-05-29 at 4 05 10 PM](https://github.com/openedx/modular-learning/assets/945577/41c41cfe-c09d-4b5b-a091-d98af9abc142)

And this one for `python_lib.zip` : 

![Screenshot 2023-05-29 at 4 04 32 PM](https://github.com/openedx/modular-learning/assets/945577/e37f4e03-5293-4b0c-a4e2-6a06b5b9daec)
