### ISSUE TITLE
[Tagging] Enable Libraries v2 on the Tagging Sandbox

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#166]
"As Axim, I can test all the new library features on [the Tagging/Taxonomy sandbox](https://tagging-preview.staging.do.opencraft.hosting/)."

Acceptance criteria:
1. The sandbox has the [Library Authoring MFE](https://github.com/openedx/frontend-app-library-authoring/) installed and enabled.
2. The [v2 Content Editors](https://github.com/openedx/frontend-lib-content-components?tab=readme-ov-file#how-to-set-up-development-workflow-of-v2-content-editors-in-studio-and-course-authoring-mfe) are enabled for v2 library content.
3. The new Library Content Block UI is enabled in Studio.

**Comment by bradenmacdonald** [comment]
@kdmccormick Do you know where I can get details on the new Library Content Block UI? (The new UI for selecting which library to import from, and which blocks within that library)

**Comment by kdmccormick** [comment]
Sorry for the delay @bradenmacdonald . [This PR](https://github.com/openedx/frontend-lib-content-components/pull/411) is the latest on greatest on that new UI. As far as I know, there are no designs or mockups informing it. I believe that Jenna and the Schema folks plan on revisting the design of that UI before we release it anywhere.
