### ISSUE TITLE
[Tagging] Download Course Tag Spreadsheet

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#172]
"As a power user in Studio, I wish to download a spreadsheet for the whole course, showing all the components in the course and which tags each one has"

**Acceptance Criteria**
1. From Studio, any user with permission to edit the course can use the new "Export Tags" menu to download a CSV that contains:
    a. Every Section/Subsection/Unit/Component of the course as its own row
    b. Every taxonomy used in the course as a column, with its [Export ID](https://github.com/openedx/modular-learning/issues/183) as the column header.
    c. A list of what tags each item has
2. The CSV should use indentation to reflect the course outline structure (see screenshot below)

**CSV Format**

Name | Type | ID | Taxonomy1 | Taxonomy2
-- | -- | -- | -- | --
Section 0: Course Introduction | Section | block-v1:... | tag1 |  
&nbsp;&nbsp;&nbsp;&nbsp;Section 0: Course Introduction | Subsection | block-v1:...  | tag3 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lesson 0.1: Course Organization | Unit | block-v1:Axim+WGU_Sample1+Test_1+type@vertical+block@51f3... | tag4,tag5,tag6
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Course Introduction | Video | block-v1:Axim+WGU_Sample1+Test_1+type@wgu_image_dams+block@55c1... | tag5,tag6 |  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Course Organization | Text | block-v1:Axim+WGU_Sample1+Test_1+type@html+block@6bad... | tag5 | easy

How the above .csv would look in Excel (note the indentation):

![Screenshot 2024-01-12 at 2 21 39 PM](https://github.com/openedx/modular-learning/assets/945577/1d5ed2dd-bf32-469c-b991-a244d6000df4)

**Notes**
* A follow-up task should implement this for libraries too
* We'll probably want to use the same CSV/spreadsheet format in the future for **bulk editing** of tags - download this spreadsheet, enter tag values into the rows/columns as needed, then upload it back into the course to have your tag changes applied. So keep that in mind.

**Comment by jmakowski1123** [comment]
This looks like it's on the right track to me! 

I see this as a stepping stone to the next epic, which would be a bulk tag import. "As a course author, I want to use this excel sheet to add tags to content and import those tags in bulk via an import workflow." Out of scope for this ticket, but just want to make sure we're aligned on future steps, yes?

**Comment by bradenmacdonald** [comment]
> I see this as a stepping stone to the next epic, which would be a bulk tag import. 

@jmakowski1123 Yes, absolutely. I did put a note about that at the end of the description ^

**Comment by Colin-Fredericks** [comment]
Seeing tabs inside a spreadsheet cell felt weird at first, but I think it's the right way to go, especially since there's no actual bottom level to edX hierarchy. We can't just do it as a set of columns. Good call.

**Comment by bradenmacdonald** [comment]
@Colin-Fredericks Yeah, that column is not really used for anything other than helping the user understand which content items are which, so I thought we might as well make it "pretty" and "helpful". I tried a format with columns at first, but it didn't really work. And this way the format can be used identically for library exports too, which have no hierarchy.

**Comment by pomegranited** [comment]
@bradenmacdonald CC @rpenido There's already a "course blocks" API endpoint that returns all the blocks in a course, see [lms.djangoapps.course_blocks.api](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/course_blocks/api.py#L57), though note:

1. It requires a `user` to be passed in, because of conditional content display rules for user cohorts.
2. It doesn't sort the blocks according to the course outline, it returns them in a non-deterministic order.
   When we needed this functionality for Insights, we ended up [sorting the blocks in the analytics pipeline](https://github.com/openedx/edx-analytics-pipeline/blob/master/edx/analytics/tasks/insights/course_blocks.py#L293-L320), because it was too difficult to put it into the transformer loop used by the API. But that functionality should live in the course blocks API IMHO.

**Comment by bradenmacdonald** [comment]
@pomegranited For this we really need a Studio course outline API, not an LMS one. I think [`learning_sequences.api.get_course_outline`](https://github.com/openedx/edx-platform/blob/11cbf0d6f77512547a9bd6ce4566489d496e57de/openedx/core/djangoapps/content/learning_sequences/api/outlines.py#L100-L108) comes close ("There is no user-specific data or permissions applied in this function.") but it doesn't include units and components. I am not sure what other APIs may be available.

If nothing else, we can always do it asynchronously the "slow" way by recursing the tree.

**Comment by pomegranited** [comment]
@bradenmacdonald  Ahh yes, I'm sorry, I keep forgetting we have to deal with draft content for Tagging.
Sorry for the noise!

**Comment by pomegranited** [comment]
@bradenmacdonald  @jmakowski1123 -- @rpenido has a good question about this requirement:

>  a. Every Section/Subsection/Unit/Component of the course as its own row

Should the actual top-level `course` block be exported too, so that we can tag courses? It's trivial to add here.

**Comment by bradenmacdonald** [comment]
@pomegranited That's a good question. I'm not sure if it's important or not. @jmakowski1123 ?

**Comment by pomegranited** [comment]
@bradenmacdonald @jmakowski1123 FYI though we don't have a UI for editing top-level "course" tags yet, but when automatic tagging is enabled, the "language" tag gets added to new courses on creation (cf https://github.com/openedx/edx-platform/pull/32907).

**Comment by pomegranited** [comment]
@bradenmacdonald @jmakowski1123 Where should the "Export tags" menu item live in Studio? There's no "course level" menu to add it to at the moment, only a bunch of buttons at the top of the Course Outline, or down the right-hand side:

![image](https://github.com/openedx/modular-learning/assets/7556571/11d60a39-39b6-4204-aae4-d8d71bd0f3f3)

**Comment by jmakowski1123** [comment]
I think it makes most sense to make the tag export available next to the course export, in the "Tools" dropdown. This is going to require a bit of UI change/input. Do we simply add another option in that menu, so that it's Tools --> Import, Export Course, Export Tags, Checklist". Or does the "Export" option come with sub-menu for Course/Tags...? cc @ali-hugo

**Comment by Colin-Fredericks** [comment]
You could put it as a separate item on the Export page itself - Export Course, Export Tags, Export All.

**Comment by jmakowski1123** [comment]
> You could put it as a separate item on the Export page itself - Export Course, Export Tags, Export All.

@Colin-Fredericks As a new user of this feature, would it be obvious enough to you to click on "export" in search of tag export, without having an obvious button from the banner?

**Comment by ali-hugo** [comment]
@pomegranited Do we need to account for _importing_ course tags, or are we only allowing exporting of course tags?

---

I agree with @jmakowski1123 that the export option should exist within the "tools" menu. I think a sub-menu listing the two export options (i.e. "export course" and "export tags"), would work well (see mocks below).

I also think it might make the options more clear if the "import" menu item were more descriptive and instead read "import course".

![menu](https://github.com/openedx/modular-learning/assets/88187719/06bf9cf6-cd7e-4618-9f82-da4d9797864d)

![sub-menu](https://github.com/openedx/modular-learning/assets/88187719/86daf603-fa6f-4a38-b65d-75760cff4f84)

**Comment by pomegranited** [comment]
@ali-hugo 

> Do we need to account for importing course tags, or are we only allowing exporting of course tags?

We need to account for both exporting and importing (importing or "bulk editing of tags" will be part of a separate ticket).

There's also the same for libraries: https://github.com/openedx/modular-learning/issues/173

**Comment by ali-hugo** [comment]
@pomegranited Great, thanks for confirming. 

I've updated the above mocks slightly; I changed "import course" back to just "import" (to allow for a sub-menu like we have on "export"). 

Unless @jmakowski1123 objects, I think this is probably good to go.

**Comment by pomegranited** [comment]
@ali-hugo these nested menus are great, but unfortunately Studio doesn't use Paragon, and implementing them acccessibly will be difficult.

@jmakowski1123 @bradenmacdonald is it ok if we add these new links to the [Course Authoring MFE StudioHeader](https://github.com/openedx/frontend-app-course-authoring/blob/4850302175853bd9a2edec41b99fdcd9be77836e/src/header/Header.jsx#L6) instead of legacy Studio?

CC @rpenido

**Comment by rpenido** [comment]
Yes @ali-hugo! Showing all the items in a single level is possible.

**Comment by bradenmacdonald** [comment]
@pomegranited Yes. From now on, we can basically focus on the MFEs only.
