### ISSUE TITLE
[Tagging] An "Export ID" identifies each Taxonomy

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#183]
"As a content author, I want a consistent way to identify taxonomies, especially across instances".

**Acceptance Criteria**

1. Each Taxonomy gets an **Export ID**
    - The Export ID is a mandatory string ID like `lightcast` or `lightcast-skills` or `io.lightcast.open-skills`
    - During the "Import a New Taxonomy" workflow, after prompting the user for the name of the taxonomy, prompt them for the "Export ID".
    - For existing taxonomies, use a data migration to set the Export ID to a slug derived from the taxonomy name.
2. (For now) The taxonomy ID cannot contain whitespace or punctuation except `.`, `-`, and `_`. Ideally, any unicode letters or non-punctuation characters should be allowed.
    - Valid: `LIGHTCAST_V17`, `lightcast-skills`, `io.lightcast.open-skills`
    - Hopefully valid `日本`, `Québec` (though if allowing these is too much effort they can be skipped for now)
    - Invalid: `LightCast Skills`, `One,Two,Three`, `Foo:Bar`, `X;Y;Z`, `"quotes"`
4. The Export ID must be unique for each Open edX instance.
5. The code and documentation for "Export ID" must clearly state that it should only be used for import/export purposes and not for any internal use like events, analytics, etc. which should use the existing database internal numeric ID. (Because we may allow the Export ID to be edited in the future).
6. The Export ID should be editable in the Django admin, but (for now) not in the UI.
7. The Export ID should be displayed on the Taxonomy Details page:
    ![Screenshot 2024-01-17 at 11 04 54 AM](https://github.com/openedx/modular-learning/assets/945577/e7726e9f-4e8a-4f6a-8239-4b34fd69ef6d)

**Comment by ChrisChV** [comment]
@bradenmacdonald One question, I should also add the Export ID in the files when exporting a taxonomy?

**Comment by bradenmacdonald** [comment]
@ChrisChV How would you do that? I don't think it's possible in the .csv format. Perhaps in the JSON format, if it won't break the format. But I don't think it's important because on import you usually set a new "Export ID", just like how the taxonomy name is also not included in the files.
