### ISSUE TITLE
Extend copy-paste UI to the Unit level (with NEW waffle flag)

### ISSUE THREAD

**Issue by ormsbee** [openedx/modular-learning#19]
For users who have opted in to the new copy-paste waffle flag:

![Screenshot 2023-06-23 at 11 27 20 AM](https://github.com/openedx/modular-learning/assets/945577/a3c546d3-85aa-42d4-b900-5d617bb17d3f)

+ Show "Copying" animation when copying, just like copying a component

![Screenshot 2023-06-23 at 11 28 08 AM](https://github.com/openedx/modular-learning/assets/945577/314b0cba-19e3-4162-9f74-79eb9bd3508b)

![Screenshot 2023-06-23 at 11 28 26 AM](https://github.com/openedx/modular-learning/assets/945577/7c592f9c-8d06-4c58-b9c9-6db902c45b04)

![Screenshot 2023-06-23 at 11 28 58 AM](https://github.com/openedx/modular-learning/assets/945577/0e3b7793-e7a5-4978-bc22-90a0b7a181d1)

![Screenshot 2023-06-23 at 11 29 09 AM](https://github.com/openedx/modular-learning/assets/945577/c9d8ab5d-d4ed-40fe-a5e4-abbf61852f00)

![Screenshot 2023-06-23 at 11 29 32 AM](https://github.com/openedx/modular-learning/assets/945577/069aac70-7656-4618-afac-69d3138ed1f2)

See wireframes in Figma for more details.

**Comment by bradenmacdonald** [comment]
Done in https://github.com/openedx/edx-platform/pull/32891
