### ISSUE TITLE
[Course Search] Trigger Course Search Modal in Course Authoring MFE

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#199]
"As a course author, I want to search for course content in the UI"

[**Figma designs**](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP?type=design&node-id=13343-23509&mode=design&t=VbZ41Idprq3JVHYe-0)

Requirements:
1. Add the 🔍 icon to the Studio header, and **show it only if a new ENV variable / feature flag is enabled**.
    ![Screenshot 2024-03-07 at 10 46 29 AM](https://github.com/openedx/modular-learning/assets/945577/4d78b96c-a171-4d1c-8349-197b94c06494)
2. Clicking the 🔍 icon should open the search modal.
3. If the user is currently in a course context, the current course ID should be passed to the search modal. If the user is on the "home page" of the course authoring MFE or the taxonomy editor or some other place, no course ID should be passed to the search modal.
4. Write basic tests. Don't spend any time on tests that cover the search results/filters as those parts of the UI will change.

Notes:
* Use [this prototype PR](https://github.com/openedx/frontend-app-course-authoring/pull/868) as a starting point. ~~It contains some TypeScript that needs to be converted to JS though.~~ Remove the keyboard shortcut for opening the modal (for now).
    ![Screenshot 2024-03-05 at 12 08 06 PM](https://github.com/openedx/frontend-app-course-authoring/assets/945577/6b4c6e4a-8f04-45bd-8bd9-2f1d848999c6)
* For now, the filters and results and other content of the modal can be as shown ^ in the prototype; implementing the UX for those is in two separate stories.
* If necessary for dealing with development constraints, coverage requirements, etc. this can be kept as a feature branch until the UX is completed.

**Comment by rpenido** [comment]
Hi @bradenmacdonald! Should we implement this in a view completely contained in the `Studio` or use an `iframe` as we did for the ContentTagsDrawer?

**Comment by bradenmacdonald** [comment]
@rpenido This should be 100% in the Course Authoring MFE. When I said "Studio header", I meant the "Course Authoring MFE header".
