### ISSUE TITLE
Need a progress indicator for the taxonomy import process

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/modular-learning#205]
As a taxonomy administrator, after I've clicked completed the final step for importing a taxonomy (adding a description), I am not given any sort of progress indicator or indication that the import process is underway. I am eventually given a notification that the import is complete, but the time in between the final step and the completion often takes around 30 or more seconds, and I'm left hanging, unsure of whether the import process is working. I'd like a notification that the import process is underway.

Possible MVP solution: After the user completes the final step in the import process, which is adding a description field, they could be presented with a notification that says something like "Import in Progress. This may take some time." They could have the option to click an "ok" button to close the notification and go about their work until the notification that the import is complete pops up.

This in-progress notification can be built using the exact same template/design as the notification for import complete, just with different text: "Import in Progress. This may take some time." See image for reference.

![Image](https://github.com/openedx/modular-learning/assets/95227019/07b99069-d7e2-46a4-adb3-312018738c8c)

**Comment by jmakowski1123** [comment]
@ali-hugo anything you'd add here?

**Comment by ali-hugo** [comment]
@jmakowski1123 Looks good to me. The only thing I'd add is some text to indicate what the user can do while the upload is processing. A few examples (@bradenmacdonald to confirm which match the capabilities of the UI):

---

**Import in progress**
Please keep this window open. We'll let you know when it's done.

---

**Importing taxonomy...**
You can keep working while we handle the import in the background.

**Comment by bradenmacdonald** [comment]
I think we need to go with the first one - "Please keep this window open. We'll let you know when it's done."

**Comment by jmakowski1123** [comment]
That's fine, we're talking like under a minute of wait time.

**Comment by ChrisChV** [comment]
@bradenmacdonald @ali-hugo @jmakowski1123 I have added the alert, but displaying the alert stops whatever is happening on the page, that is, the import is paused. The user has to click OK to continue with the import. Wouldn't that cause more confusion? Maybe the user is left waiting without closing the alert?

https://www.loom.com/share/d3ef423ee4d6460190df1185a85ae522?sid=7af2e657-0205-4b67-a0df-b1ed7258de48

**Comment by bradenmacdonald** [comment]
@ChrisChV  Can you please implement the alert using Paragon [Toast](https://paragon-openedx.netlify.app/components/toast/)? Then it won't block the page.
