### ISSUE TITLE
[Tagging] Change behaviour of Tag Drawer on click outside

### ISSUE THREAD

**Issue by ChrisChV** [openedx/modular-learning#209]
"As a course author, I don't want to lose the edited tags if I click outside the tag drawer"

Design: [Figma](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP?type=design&node-id=13585-6449&mode=design&t=hgTeNriivLM74TtO-4)
Depends on https://github.com/openedx/modular-learning/issues/190

###  Acceptance Criteria

If the user clicks on the grey area outside of the tagging drawer AND there are unsaved changes (at least one added/removed tag):

a. The drawer does not close
b. The footer of the drawer animates to draw the user's attention to the actions (see [Figma](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP?type=design&node-id=13585-6449&mode=design&t=hgTeNriivLM74TtO-4)). Perhaps like [Blink 2 at this link](https://webcode.tools/css-generator/keyframe-animation)

### Developer notes

- Only implement this on frontend-course-authoring screens.
- Possible ways to implement this:
    - Verify that no component of the drawer has been clicked, [like this code](https://github.com/openedx/frontend-app-course-authoring/blob/master/src/content-tags-drawer/ContentTagsCollapsible.jsx#L358). All components need to be mapped, it is complicated and susceptible to errors.
    - The Sheet component has a way of knowing if it has [been clicked outside](https://github.com/openedx/paragon/blob/master/src/Sheet/index.jsx#L67). We could add a parameter to use that function publicly

**Comment by ChrisChV** [comment]
@bradenmacdonald

**Comment by bradenmacdonald** [comment]
@ChrisChV What currently happens if the user clicks outside - their changes are lost? If so we need to fix this ASAP. If "nothing" happens, it's less urgent.

**Comment by bradenmacdonald** [comment]
@ChrisChV  Actually from looking at [the code](https://github.com/openedx/paragon/blob/d67a04f6973df56172f218f57444af3575c10fbc/src/Sheet/index.jsx#L67), doesn't the `blocking` parameter already do what we want? If we set `blocking={true if unsaved changes else false}` that would at least prevent the users from losing their work, right?

**Comment by ChrisChV** [comment]
> @ChrisChV Actually from looking at [the code](https://github.com/openedx/paragon/blob/d67a04f6973df56172f218f57444af3575c10fbc/src/Sheet/index.jsx#L67), doesn't the blocking parameter already do what we want? If we set blocking={true if unsaved changes else false} that would at least prevent the users from losing their work, right?

@bradenmacdonald Yes that solves this: `a. The drawer does not close`, but it is not possible to do this: `b. The footer of the drawer animates to draw the user's attention to the actions`

**Comment by bradenmacdonald** [comment]
@ChrisChV  I see. Well if it's going to be a lot of work to implement the animation we may decide to do without it for now, until we get user feedback. But we definitely don't want users losing their work if they click off of the tag drawer.
