### ISSUE TITLE
Issues when importing a large taxonomy

### ISSUE THREAD

**Issue by ChrisChV** [openedx/modular-learning#213]
When importing a large taxonomy, like the `Light Cast Taxonomy`, it takes a long time (10-15min+) for the `/import` request to complete successfully. In some cases, it takes longer, and the memory usage fills up resulting in the cms container restarting.

When that happens, we get the alert error, however we can see the imported taxonomy in the list, containing all the tags. For smaller taxonomies (like `two level` and `languages`) it works fine, and medium sized (like `FlatTaxonomy`) it takes 3-4min to complete successfully.

###  Acceptance Criteria

- Check the problem further and provide a solution

**Comment by bradenmacdonald** [comment]
Thanks for reporting this @yusuf-musleh  and @ChrisChV. The memory usage should be more or less constant, and not increase with the size of the taxonomy. So we definitely need to fix it.
