### ISSUE TITLE
[Libraries] [Collections] [Backend] Collections model in Learning Core

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#225]
Define new `Collection` Model with the following fields in a new `collections` app in the `openedx_learning` repo:

- id: models.AutoField(primary_key=True)
- context: ForeignKey to the LearningPackage (which is a 1-to-1 with ContentLibrary) instance this collection belongs to
	- name
	- description
	- date_created
	- date_updated
	- enabled
	- allow_multiple
	- ... possibly other fields - see collections design in Figma

Create a python API for CRUD operations on these collection objects, and appropriate test cases.

**Comment by rpenido** [comment]
Hi @bradenmacdonald! CC @pomegranited 

Do you think this should live in `openedx-learning`?
If this is the case, the `context` should be just a `string` field (with no validation) with the key to the library, as we don't have `OpaqueKey` or other entities from `edx-platform` here, right?
