### ISSUE TITLE
[Libraries] [Collections] [Backend] REST CRUD API for Collections in v2 Libraries

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#226]
1. Define new CRU<strike>D</strike> REST API to be able to query/manipulate the instances of the newly created Collection Model (https://github.com/openedx/modular-learning/issues/225). 
   - Don't implement "Delete" -- just raise a 405 for now. Will be handled by https://github.com/openedx/modular-learning/issues/231.
2. These should be defined in edx-platform (in the `content_libraries` django app) to handle permission checks and interface with the Collection model defined in `openedx_learning` repo.
   - Similar to how the taxonomy [views](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/content_tagging/rest_api/v1/views.py) and [apis](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/content_tagging/api.py) are implemented.
   - For permissions, use the ContentLibrary associated with the Collection's LearningPackage to determine the user's permissions on the Collection. If the LearningPackage is not associated with a ContentLibrary, raise an error.
3. We also need to emit events when collections are created/edited/updated, which will require adding new event & data types to https://github.com/openedx/openedx-events

**Comment by pomegranited** [comment]
@bradenmacdonald To clarify: we should use the ContentLibrary associated with the Collection's LearningPackage to determine the user's permissions on the Collection?
