### ISSUE TITLE
[Libraries] [Collections] [Backend] Add tags to collections

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#228]
Update the edx-platform tagging/content_library APIs so that users with appropriate permissions can add/remove tags from collections. No changes to `openedx-learning` are expected for this ticket.

Notes:
- We can use the existing tagging mechanism, i.e. create an `ObjectTag` instance where `object_id` would be the key of the Collection being tagged
    - However, to do that we need to extend object_id field to support more keys, currently it [only supports](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/content_tagging/api.py#L393) `CourseKey`, `LibraryLocatorV2` or a `UsageKey`.
- We likely need to create a new type of [key](https://github.com/openedx/opaque-keys/blob/master/opaque_keys/edx/keys.py), `CollectionKey` in the opaquekeys repo, that could look something like: `lib-collection:org:lib:collection-id`.
  The Collection's `org` can be pulled from the associated ContentLibrary.

**Comment by pomegranited** [comment]
Part 2 of this ticket:

* Build on https://github.com/openedx/modular-learning/issues/229 to add the `object_key` and `tags` field to the collection's Meilisearch index, using the same format as used for tagged components.

**Comment by pomegranited** [comment]
Backend changes have been deployed to the sandbox; nothing to AC test here :)
