### ISSUE TITLE
[Libraries] [Collections] [Backend] store component-collection association in Studio Library Index

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#230]
This step implements the different moving parts of updating Collections data to Library Component documents in Meilisearch. To do that we need to:
  - Extend the search [`Fields`](https://github.com/openedx/edx-platform/blob/0b45e991280933279c9409266d8904922567879a/openedx/core/djangoapps/content/search/documents.py#L20) class to include `collections`
  - Since there can be multiple collections, that field would be an array
  - Add an `upsert_block_collections_index_docs` function updates the collections data in documents for the given library block (similar to [upsert_block_tags_index_docs](https://github.com/openedx/edx-platform/blob/0b45e991280933279c9409266d8904922567879a/openedx/core/djangoapps/content/search/api.py#L476))
  - Rename existing event [`CONTENT_OBJECT_TAGS_CHANGED`](https://github.com/openedx/openedx-events/blob/main/openedx_events/content_authoring/signals.py#L207) to `CONTENT_OBJECT_ASSOCIATIONS_CHANGED` and add a data field to indicate which associations have changed (`tags` or `collections`).
    This event fires when the library component/object’s tags or collections change, and hence would call the new upsert function to update the tags and/or collections in the documents in meilisearch

Added to this issue:
- Trigger collection (re)indexing for new and updated collections, cf https://github.com/openedx/modular-learning/issues/229 + events created for https://github.com/openedx/modular-learning/issues/226

**Comment by pomegranited** [comment]
Backend changes have been deployed to the sandbox; nothing to AC test here :)
