### ISSUE TITLE
Add Meilisearch to tutor core

### ISSUE THREAD

**Issue by pomegranited** [openedx/modular-learning#236]
Meilisearch must be deployed and enabled to support Libraries v2, and course content searching in the Authoring MFE.
Additionally, there's a Meilisearch engine for courseware and course discovery content search.

Currently, [meilisearch is in an optional plugin](https://github.com/open-craft/tutor-contrib-meilisearch), but we want it to be installed and enabled in Tutor by default.

Part of: https://github.com/openedx/frontend-app-authoring/issues/1334 

- [x] Integrate this plugin into Tutor core
- [x] Enable it by default
- [x] Allow connections to remote instances
- [x] Include the k8s support provided by the [plugin's patches](https://github.com/open-craft/tutor-contrib-meilisearch/tree/main/tutor_meili/patches)
- [x] Consider providing `SEARCH_ENGINE = "search.meilisearch.MeilisearchEngine"` to the LMS / CMS settings to use https://github.com/openedx/edx-search/pull/162 
- [x] <strike>Remove the meilisearch plugin from the Tutor plugins index: https://github.com/search?q=repo%3Aoverhangio%2Ftpi%20meilisearch&type=code</strike> -- Meilisearch is now in tutor master, but not yet in nightly, so this plugin is still useful there.

**Comment by regisb** [comment]
Here's the PR: https://github.com/overhangio/tutor/pull/1141
