### ISSUE TITLE
Bug: Hide Legacy Library content button in legacy Studio when Libraries v1 are disabled

### ISSUE THREAD

**Issue by pomegranited** [openedx/modular-learning#237]
Legacy Library green button doesn't disappear when you disable legacy libraries, whether by waffle flag or the big ENABLE_CONTENT_LIBRARIES feature flag.

![image](https://github.com/user-attachments/assets/36791934-d44b-4581-96d6-cd98f3573bb1)

**Comment by pomegranited** [comment]
@jmakowski1123 @lizc577 @sdaitzman @marcotuts This is ready for AC testing on the sandbox. Please see the Testing Instructions on https://github.com/openedx/edx-platform/pull/35736 for how to test this -- it requires Django Admin access to change some waffle flags.

**Comment by ChrisChV** [comment]
@jmakowski1123 @lizc577 @sdaitzman @marcotuts Friendly reminder that this is ready for AC testing on the sandbox.
