### ISSUE TITLE
Hide "Library Content" and "Problem Bank" buttons in Legacy Library UI.

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#238]
Per @kdmccormick: "New library blocks and ProblemBank blocks can both be added to Legacy Content Libraries with big green buttons. Even if that managed to work correctly, we shouldn't be encouraging users to do this."

![Screenshot](https://github.com/user-attachments/assets/641e7626-c778-4b5c-b173-db13231036e7)

**Comment by navinkarkera** [comment]
@jmakowski1123 @lizc577 @sdaitzman @marcotuts This is ready for AC testing on the sandbox

**Comment by sdaitzman** [comment]
No longer appearing for me, looks good!
