### ISSUE TITLE
Add search functionality on content in libraries

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/modular-learning#36]
- [ ] https://github.com/openedx/modular-learning/issues/37

**Comment by marcotuts** [comment]
Note - This made be connected to the work we are doing for Content Library Authoring (FC-0045)

**Comment by jmakowski1123** [comment]
Yep, this is just a placeholder ticket. Once Braden gets all the epics created for the Library MVP, I'll go through and either close to merge the placeholders.
