### ISSUE TITLE
Technical discovery: Analyze ERDs related to tagging

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/modular-learning#44]
Some tagging services already exist. This is a [list of tagging-related ERDs](https://lucid.app/lucidchart/ac49c90e-9718-4f37-9135-f3c0c9a62017/edit?invitationId=inv_8f93357e-0a72-440f-a91a-19f94e78d2a5&page=XgRuhr3f3WXf#). For each of these, we need to answer:

What services already exist to capture tags?
What use cases do they serve?
Who owns what data?
Are they still used/supported?
Make a call to deprecate

**Comment by bradenmacdonald** [comment]
Not sure if https://github.com/openedx/taxonomy-connector is included in the ERDs listed above, but it's one of the main ones to evaluate.

**Comment by giovannicimolin** [comment]
@jmakowski1123 I'll be working on this in the current sprint and post updates here as I go.

**Comment by giovannicimolin** [comment]
**WIP**

What services already exist to capture tags?

**1. Taxonomy Connector (https://github.com/openedx/taxonomy-connector)**

This is a Django app that lives inside course-discovery and has tagging and taxonomy capabilities.

_What use cases do they serve?_
It’s used to capture tags for courses and programs, and supports taxonomies. Used by the marketing site and course/program management tools in the Open edX platform.

Recent work done on BD-53 ([Video and Unit Skill Tagging](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3574726665/BD-53+Video+and+Unit+Skill+Tagging)) by OpenCraft added support for tag video blocks and units (and it’s extensible to support other block types). The block tagging is done automatically using an external service and users confirm the tags on prompts that appear at the end of units/videos.

_Who owns what data?_

The discovery service.

_Is this still used/supported?_

Yes.

_Make a call to deprecate?_

Depends on the approach with the modular learning implementation:

If we decide to implement replacements **that only support content from learning core** (`v3/Denver`), then we can only deprecate these features once learning core becomes the main source of content served by Open edX.

If we decide to support **both the old and new systems using a single tagging service**, then we can deprecate and replace these features as soon as the new system is up and running.

----

I'll keep digging through the other tagging services and entities that were not covered by this.

**Comment by bradenmacdonald** [comment]
@giovannicimolin Nice summary, thanks. I have also found [Structured Tagging based on XBlockAsides](https://github.com/openedx/edx-platform/blob/9171914ed7b6fd27f84beceb542707e06432aac0/cms/lib/xblock/tagging/tagging.py) in the codebase, which [has a UI](https://github.com/openedx/edx-platform/blob/db32ff2cdf678fa8edd12c9da76a76eef0478614/cms/templates/structured_tags_block.html) and [a taxonomy?](https://github.com/openedx/edx-platform/blob/db32ff2cdf678fa8edd12c9da76a76eef0478614/cms/lib/xblock/tagging/models.py), but I'm not sure how it works. There is also code for [tagging users](https://github.com/openedx/edx-platform/blob/db32ff2cdf678fa8edd12c9da76a76eef0478614/openedx/core/djangoapps/user_api/models.py#L147-L179).

**Comment by giovannicimolin** [comment]
@bradenmacdonald Nice finds! I'll add those to my comment above.

**Comment by giovannicimolin** [comment]
@bradenmacdonald @jmakowski1123 I think I covered the original issue asks in my comment above. This is ready for a review.

About the deprecation: should we start the DEPR process for those repos now, even not having the substituting implementation complete?

**Comment by giovannicimolin** [comment]
@jmakowski1123 Friendly nudge to review this.
