### ISSUE TITLE
Update tech specs with decisions from frames v1

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/modular-learning#46]
Update the Technical Approach document so that it encompasses all the new UI elements required for launch.

**Comment by jmakowski1123** [comment]
This is complete: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3575611457/Phase+1+Technical+Approach+Content+Reuse+MVP+Studio+Copy+Paste#UX:-Studio-Clipboard

**Comment by bradenmacdonald** [comment]
@jmakowski1123 Thanks for updating that section. I have reviewed it and it looks good. There are still some things phrased as open questions below that in the document, so I pinged folks on them. It looks like we have the plan mostly fleshed out though :)

**Comment by ali-hugo** [comment]
@jmakowski1123 Thanks for tackling the updates to the wiki! I've left 2 comments for you. 
P.s. I will also replace the Figma screenshots with screenshots with comments hidden.
