### ISSUE TITLE
Move existing Studio component actions into a menu

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#50]
When viewing/authoring components in Studio:

Move most of these buttons:
![Screenshot 2023-02-17 at 2 06 02 PM](https://user-images.githubusercontent.com/945577/219802874-29417fce-9cfe-4d39-95fa-f42a764cc2c9.png)

Into a menu like this:
![Screenshot 2023-02-17 at 2 08 01 PM](https://user-images.githubusercontent.com/945577/219802990-86613a77-ee08-4cab-b72c-6331f69474c3.png)

Exclude the new "Copy" menu item from the scope of this task; it will be added in #10 .

**Comment by bradenmacdonald** [comment]
@jmakowski1123 @cablaa77 For this specific change (moving these actions from the toolbar into the dropdown menu, but _without_ the new copy/paste functionality for now), do you want this to be isolated behind the feature flag for copy-paste (more work but only the chosen beta testers will see any changes in Studio) or can we just make this change now (everyone starts using the new menu instead of the icons, and later the chosen beta testers will see the "Copy" item show up in the menu once we're ready to test).

**Comment by jmakowski1123** [comment]
> @jmakowski1123 @cablaa77 For this specific change (moving these actions from the toolbar into the dropdown menu, but _without_ the new copy/paste functionality for now), do you want this to be isolated behind the feature flag #11 for copy-paste (only the chosen beta testers will see any changes in Studio) or should we just make this change now (everyone starts using the new menu instead of the icons, and later the chosen beta testers will see the "Copy" item show up in the menu once we're ready to test).
> 
> Either way is fine from my perspective :)

This decision will impact edx user first, so I defer to @cablaa77 to make the final call. I'd lean toward keeping it isolated behind the feature flag for now, in favor of rolling out the new menu and the new copy item at the same time.

**Comment by cablaa77** [comment]
Please keep it isolated behind the feature flag for now and we can roll out
the new menu and copy items at the same time. Thanks.

Best regards,
Brad
