### ISSUE TITLE
Change "Copy" in the component actions menu to "Copy to clipboard"

### ISSUE THREAD

**Issue by ali-hugo** [openedx/modular-learning#57]
Change the wording of the "Copy" menu item in the component actions menu to "Copy to clipboard":

<img width="959" alt="Screenshot 2023-05-16 at 8 11 09 AM" src="https://github.com/openedx/modular-learning/assets/88187719/e56f4d0b-cd6d-49e6-a924-bf231d5ff6d1">

---

#### Why was this decision made?

Feedback from usability testing revealed some confusion after "copy" was selected; because the toast message ("copying") only shows for a short period of time, and there is no confirmation that the component was indeed copied, users felt unsure of what to do next. By mentioning a "clipboard" in the menu item, users may draw from previous knowledge of how clipboards work and understand that the item has been copied into some kind of temporary storage.

**Comment by ali-hugo** [comment]
@bradenmacdonald I've created this issue but don't seem to be able to adjust the assignee or the project. Can you do that from your side?

**Comment by bradenmacdonald** [comment]
Thanks @ali-hugo - done! And I added this to Milestone 2. CC @jmakowski1123

**Comment by bradenmacdonald** [comment]
Done: https://github.com/openedx/edx-platform/pull/32339
