### ISSUE TITLE
[Tagging] Implement Taxonomy Data Architecture models + APIs

### ISSUE THREAD

**Issue by ChrisChV** [openedx/modular-learning#63]
**Full description**

Implement the data models and APIs described in the [discovery document](https://docs.google.com/document/d/13zfsGDfomSTCp_G-_ncevQHAb4Y4UW0d_6N8R2PdHlA/edit#heading=h.ogslfhqqejyh)

**Completion criteria**

- PR against openedx-learning implementing the models and APIs for Taxonomy, Tag, ObjectTag
- PR against edx-platform which implement OrgTaxonomy and ContentTag
- Automated testing must cover common paths in behavioral specification.

**Comment by pomegranited** [comment]
Hi @ormsbee !

For the 2nd part of this issue, I need to add `openedx-learning` as a dependency for edx-platform, so that I can subclass the Taxonomy and ObjectTag classes under `openedx.features.tagging`. I we at least need to do the following steps first, but is there anything else you want done for this initial release?

* tag a release - v0.1 ?
* publish to pypi

**Comment by ormsbee** [comment]
@pomegranited: Please let me merge https://github.com/openedx/openedx-learning/pull/51 before anything gets published to pypi – there are some MySQL-related issues I'm sorting out there w.r.t. collation and index sizes.

I'm working on that PR now and hope to have it in reviewable state by end of day.

**Comment by pomegranited** [comment]
No worries @ormsbee -- but it does make me wonder whether openedx-tagging should be in its own separate repo from openedx-learning? I don't want to rush these important first steps for oel_learning, and tagging is a completely separate package.

**Comment by pomegranited** [comment]
@ormsbee 

> Please let me merge https://github.com/openedx/openedx-learning/pull/51 before anything gets published to pypi – there are some MySQL-related issues I'm sorting out there w.r.t. collation and index sizes.

Roger that, and thanks for those changes!

I don't have enough permissions on openedx-learning to perform the [pypi publish steps outlined in edx-platform's github.in](https://github.com/openedx/edx-platform/blob/master/requirements/edx/github.in#L15-L19). Would you be willing to do this part?
