### ISSUE TITLE
Discovery: "Bubble up" errors and warnings from components to the unit page.

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#69]
![Screenshot 2023-06-23 at 11 31 54 AM](https://github.com/openedx/modular-learning/assets/945577/e30cdcea-a5bd-4750-82f0-3b1d8845b766)

**Comment by bradenmacdonald** [comment]
@ormsbee We'd like to display on the course outline page when there are issues with a component in a [newly-pasted] Unit, such as mis-matched content groups.

For a newly-pasted Unit, it should be fine to just iterate over the contents to scan for issues after pasting, but it would be nice if these sort of errors always "bubbled" up to the outline page, regardless of whether or not the unit was recently pasted. However, I think that would require a very expensive scan over all the blocks in the course to achieve, so is probably not doable. Any thoughts?

**Comment by ormsbee** [comment]
I agree that it's not really feasible with the data as it exists today, at least not for large courses.
