### ISSUE TITLE
Copy subtitles for video blocks when VAL is not used

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#71]
https://github.com/openedx/edx-platform/pull/32346#discussion_r1241224302

**Comment by bradenmacdonald** [comment]
@ormsbee How does one go about not using VAL? From what I can see, [the feature flag is unused](https://github.com/search?q=repo%3Aopenedx%2Fedx-platform+VIDEO_ABSTRACTION_LAYER&type=code) and `edxval` is installed by default and [required](https://github.com/openedx/edx-platform/blob/5ccdd2126f7794ef220e27dd2b0663258a2bc566/cms/djangoapps/contentstore/views/videos.py#L26) [(2)](https://github.com/openedx/edx-platform/blob/5ccdd2126f7794ef220e27dd2b0663258a2bc566/xmodule/video_block/video_handlers.py#L15) by some core modules.

(Re-posting since I accidentally asked you this on the wrong issue.)

**Comment by ormsbee** [comment]
@bradenmacdonald: It's not that edx-val can be disabled, but the VideoBlock doesn't necessarily have to use it. VideoBlock knows to query VAL if there is a `edx_video_id` attribute present, but it will fall back to its own various video source and transcript related attributes if there is no `edx_video_id`.

**Comment by bradenmacdonald** [comment]
@ormsbee Ah, right. Thanks :) I'll check into that.

**Comment by bradenmacdonald** [comment]
We looked into this and it seems like `edx_video_id` is always present, so will close this unless we get reports of some workflow that we haven't yet discovered which doesn't work.
