### ISSUE TITLE
[Tagging] Implement System Tagging data architecture models

### ISSUE THREAD

**Issue by pomegranited** [openedx/modular-learning#77]
### Story

"As a taxonomy administrator, I want to be able to use system taxonomies created and maintained by the platform, so that some common taxonomies like Language, Author, and and Organization are available for content authors, whose "tags" are dynamically generated."

### Full description

Implement the data models described in the [discovery](https://docs.google.com/document/d/1k2-ziCkCGT8AcGh2zorVinF0MH-2bF6_mAl0SFxr7EQ/edit?usp=sharing) for https://github.com/openedx/modular-learning/issues/61.

### Completion criteria
 * PR against openedx-learning implementing the models for SystemTaxonomy
 * PR against edx-platform which implements any Content-side models
 * Automated testing must cover common paths in behavioral specification.

### Documentation updates & improvements criteria
 * Ensure that all models and APIs are fully documented, so that anyone using them is clear on their arguments and consequences.

### Relevant repositories
 * https://github.com/openedx/openedx-learning
 * https://github.com/openedx/edx-platform

**Comment by ChrisChV** [comment]
@pomegranited @bradenmacdonald I think we can close this issue
