### ISSUE TITLE
[Tagging] Implement content event signals

### ISSUE THREAD

**Issue by pomegranited** [openedx/modular-learning#78]
### Story

"As a openedx developer, I want to use content creation/edition events, and so I could attach new tagging pipelines when content is created or published."

### Full description

Follows on from https://github.com/openedx/modular-learning/issues/77
Prerequisite for https://github.com/openedx/modular-learning/issues/79

As described in the [System Taxonomy discovery](https://docs.google.com/document/d/1k2-ziCkCGT8AcGh2zorVinF0MH-2bF6_mAl0SFxr7EQ/edit#heading=h.3wqry1vunysp), we need to create events triggered by content creation and editing. The necessary contents follow the [MVP requirements table](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3695247491/Content+Tagging+Approach+MVP). Events are needed for:
 * Course creation and edition.
 * Course Unit creation and edition.
 * Course Component creation and edition.
 * Library creation and edition.
 * Library Component creation and edition.

 This [doc](https://openedx-events.readthedocs.io/en/latest/) is a good start point to know how openedx-events works.

### Completion criteria

 * PR against openedx-events and edx-platform with new content creation/edition events.
 * PR against openedx-learning to update the [automatic tagging ADR](https://github.com/openedx/openedx-learning/blob/main/docs/decisions/0013-system-taxonomy-auto-tagging.rst): Put `openedx-filters` under the rejected options and replace the decision with openedx-events.
 * Automated testing must cover common paths in behavioral specification.

### Documentation updates & improvements criteria
 * Ensure that all events are fully documented, so that anyone using them is clear on their arguments and consequences.

### Relevant repositories
 * https://github.com/openedx/openedx-events
 * https://github.com/openedx/edx-platform
 * https://github.com/openedx/openedx-learning

**Comment by rpenido** [comment]
@pomegranited I think we can close this!
