### ISSUE TITLE
[Tagging] Automatically add system tags for Language (to courses and course content)

### ISSUE THREAD

**Issue by pomegranited** [openedx/modular-learning#79]
### Story

"As a content author, I want the system to maintain automatic tags on my content so that I don't have to perform these tasks manually when creating/updating content."

### Full description

Follow up to
* https://github.com/openedx/modular-learning/issues/77
* https://github.com/openedx/modular-learning/issues/78

Implement automatic tagging for the system taxonomies defined in the MVP. These tags should be created/updated automatically from the content itself, triggered by the create/update events for courses and course blocks provided by https://github.com/openedx/modular-learning/issues/78

### Acceptance criteria

Language system taxonomy:
* When the user creates a new course or component ("XBlock") within a course:
    * a new ObjectTag for that object is created against the Language Taxonomy, with its Tag set to the content author's preferred language or browser language.
* When the user updates an existing course, block, library, or library block:
   * if the object already has a Language ObjectTag, no change is made to that tag. (A future ticket will make this language tag editable by content authors, and so their changes must be preserved.) 
   * if the object does not have an Language ObjectTag, one is created, using the editing content author's preferred language or browser language.
* When the user deletes a course or course xblock:
   * any existing tags for this object are deleted (this should already be handled by our tagging system).
* When an operator runs the "update tags" management command with a given "content author user ID" and a list of course, or course block IDs, a new Language ObjectTag is created if one does not already exist.

### Future work

https://github.com/openedx/modular-learning/issues/97 will implement the same thing for library blocks.

### Documentation updates & improvements criteria

* Ensure that the management command and its options are fully documented.

### Relevant repositories

* `openedx.features.content_tagging`: https://github.com/openedx/edx-platform
* `oel_tagging`: https://github.com/openedx/openedx-learning
* `openedx-events`: https://github.com/openedx/openedx-events

**Comment by pomegranited** [comment]
Note: split this into 3 separate tasks, awaiting prioritization of the other system tags:
* https://github.com/openedx/modular-learning/issues/90
* https://github.com/openedx/modular-learning/issues/91

**Comment by bradenmacdonald** [comment]
We are going to split the libraries part of this into a separate task for next sprint and focus on course blocks in this sprint (which is almost done).

@jmakowski1123 I need your call on something: for libraries we don't currently have a way to tell what language should be used when a new library block is created. We are considering adding a new setting for each library that determines the language of all the content in the library, just like courses have a language field that defines the language of the course. Would that make sense? Or would you prefer we try to support multiple languages within a library, based on the preferred language of the user who created each block?

CC @rpenido

**Comment by jmakowski1123** [comment]
Thinking to future state of libraries, we'll want libraries to support multiple languages within a library. As we think ahead to libraries being built/shared at the org level, there will be use cases where one library may have content in different languages.

**Comment by bradenmacdonald** [comment]
@jmakowski1123 OK, good to know. So in that case, how should we decide what language tag to apply when a user creates a block in a library? Or should we let the user set those manually in the future?

**Comment by jmakowski1123** [comment]
Language is a tag that would be added at the block level, right? (as oppose to at the library level). Could language be auto-added based on a read of the content, but we give authors permission to change it if it's applied incorrectly?

**Comment by bradenmacdonald** [comment]
@jmakowski1123 Yes, language will be a tag applied at the block level. And yes authors can override it. And yes, language _could_ be auto-detected from the content itself but that would definitely be too complex for the MVP so we'll need to do something dumber like use the default language of the author, or the same language as the previous block in the library, or something simple like that.

**Comment by jmakowski1123** [comment]
That sounds fine. I just want to get around the need for an author to manually add language to each block, each time.

**Comment by bradenmacdonald** [comment]
@jmakowski1123 @rpenido I have moved the library blocks language tagging to a new ticket, https://github.com/openedx/modular-learning/issues/97 .
