### ISSUE TITLE
[Tagging] Clean up Tagging models

### ISSUE THREAD

**Issue by pomegranited** [openedx/modular-learning#85]
### Story

"As an Open edX developer, I want the Open edX Tagging and Content Tagging models to be as clearly delineated and simple as possible, so that developing new tagging use cases is straightforward."

### Description

While implementing https://github.com/openedx/modular-learning/issues/63 and https://github.com/openedx/modular-learning/issues/77, we ended up using custom Taxonomy and custom ObjectTag classes to achieve the goals of the tagging MVP. There was a lot of back-and-forth on these PRs and changes in direction, and while the result works fine, it could be cleaner.

See comments:

* https://github.com/openedx/openedx-learning/pull/67#discussion_r1274124594
* https://github.com/openedx/openedx-learning/pull/67#discussion_r1275268873
* https://github.com/openedx/openedx-learning/pull/67#discussion_r1275279464
* https://github.com/openedx/openedx-learning/pull/67#pullrequestreview-1548266337
* https://github.com/openedx/openedx-learning/pull/67#issuecomment-1652239866 (inspiration, not a directive that must be addressed)
* https://github.com/openedx/openedx-learning/pull/59#issuecomment-1662517886 (re APIs)

### Completion criteria

* Read the above referenced comments, and address what you think is reasonable here.
* Review the use of the Taxonomy and ObjectTag subclasses in oel_tagging and content_tagging, and refactor to ensure that the encapsulation makes sense for these models.
* Use mixins wherever practical to make logic available when subclassing.
* Review all the model `get` and `filter`/`exclude` clauses used in oel_tagging and content_tagging, and ensure that the appropriate indexes and unique_together constraints are in place.
* Review and update ADRs to ensure they reflect the approach decided here.

### Documentation improvements

* Updating the ADRs should be sufficient documentation for this change, but also ensure that any changes to classes or their methods is reflected in their docstrings.

### Relevant repositories

* oel_tagging: https://github.com/openedx/openedx-learning
* content_tagging: https://github.com/openedx/edx-platform

**Comment by rpenido** [comment]
Clean duplicated rules with same implementation:

https://github.com/openedx/openedx-learning/blob/f73adefbcf9748dafe8ebfb7e8e6590df6780bb2/openedx_tagging/core/tagging/rules.py#L71
 
https://github.com/openedx/edx-platform/blob/98fda4110056077fbdd325f325ad8fcf76460124/openedx/features/content_tagging/rules.py#L113

**Comment by ChrisChV** [comment]
@pomegranited @bradenmacdonald I think we can close this issue
