### ISSUE TITLE
Copy/paste performance testing

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#87]
Using the sandbox at https://clipboard-preview.do.opencraft.hosting/ , test the performance of copying and pasting extremely large units that have something like ~25, 50, 100, and 500 XBlocks in them, including some with static asset files. Get a rough idea of how long the copy and paste operations each take as a function of the number of xblocks and/or size of the static files.

Why: we need to decide if we're going to use a fully asynchronous (celery task) operation for copying/pasting subsections and sections in the course. For now, we can simulate and measure this using large units. We may also want to make the unit copy/paste asynchronous too, depending on our findings.

Depends on https://github.com/openedx/edx-platform/pull/32891

**Comment by bradenmacdonald** [comment]
@ormsbee FYI. Anything to add to this task description?

**Comment by ormsbee** [comment]
@bradenmacdonald: No, it looks good to me, ty!

**Comment by bradenmacdonald** [comment]
Findings have been shared at https://docs.google.com/document/d/1zpgwiDuIWJIPjlN6vNASkEfGy2JNrCqQTCTsT5UrQ1Q/edit and we have updated our future plans accordingly (seems like no need for async). Marking this as done.
