### ISSUE TITLE
Discovery: searching draft content with keyword and filtering by content tags

### ISSUE THREAD

**Issue by pomegranited** [openedx/modular-learning#88]
### Story

"As a content author, I want to be able to search my course content in Studio and locate sections, subsections, units, and block components whose titles and/or content match my keywords, so that I can effectively navigate my course during its development."

"As a content author, I want to be able to filter keyword search results for my course content in Studio based on tags that users or the system have added to my content."

Ditto for content libraries v2.

### Full description

Investigate and plan implementation for indexing Studio (draft) content and storing associated (implicit and explicit) content tags.

This feature must:
* Index draft course outline components (sections, subsections, units), draft components (blocks), v2 content libraries and blocks, content tags, and content types.
  * The search index will be updated incrementally whenever a change is made to the draft course content, which is what is visible in Studio.
  * XBlock `index_dictionary` fields will be indexed so that the keyword search works similarly to the existing LMS course/library content search [edx-search](https://github.com/openedx/edx-search).
* Allow keyword and/or tag searches for a single learning context (e.g. course or content library)
* Searching across multiple learning contexts is out of scope for MVP.
* Return the section, subsection, and unit display names (titles) with matching course outline and component blocks, or the library title with matching library blocks.
* Allow filtering of search results based on content type, content org, and/or content tags.
* Allow fetching of all content types and content tags applied to a given learning context (for use when constructing options in the search UI).
* Allow fetching of the total count of all content tags applied to a given course outline or content component (counting both "implicit" and "explicit" tags).
* Allow fetching of the count of content tags "per taxonomy field" applied to a given course outline or content component (counting both "implicit" and "explicit" tags).
* Use OpenSearch as the backend storage (cf [DEPR-170](https://discuss.openedx.org/t/deprecation-removal-depr-170-move-from-elasticsearch-to-opensearch/5844/10)) 
 
Other desirable features:
* Return the number of times a keyword appears in the matching records.
* Allow search rankings to be boosted based on content type (e.g. show video blocks first, then text, then discussions).

### Completion criteria

* Data & system architecture prepared and approved by @ormsbee and @bradenmacdonald 
* Itemized implementation plan with estimates submitted to support a Statement of Work for this feature.

### Relevant repositories

* edx-search (indexes LMS course content): https://github.com/openedx/edx-search
* edx-events (event triggers for content changes): https://github.com/openedx/edx-events
* XBlock [IndexInfoMixin](https://github.com/openedx/XBlock/blob/35cbd6d402b7818112f531af33aa65df8c257af0/xblock/mixins.py#L547)
* oel_tagging: https://github.com/openedx/openedx-learning

**Comment by bradenmacdonald** [comment]
@pomegranited Very nice writeup!

> Searching across multiple learning contexts is out of scope for MVP.

@pomegranited @jmakowski1123  If we're only searching in one course at a time (which is perfect for the MVP), then we probably don't really need an org filter or org tags in the MVP either? Every piece of content in the course will be from the same org. (Unless it's from a content library made by a different org, but I don't think that's even possible to achieve in the platform today; that would come after the future library improvements.)

I would also suggest that when doing the UX and the dev, we try to design it so that it can work across all courses and libraries in the future without needing too many changes.

**Comment by pomegranited** [comment]
@bradenmacdonald  Since we can glean `org` from the content ID, should this be included in the index too (along with `content type`), even though we don't technically need it right now?

**Comment by bradenmacdonald** [comment]
Yes, you might as well put it in, because we'll want to have it in the index when we allow searching across all courses/libraries in the future.

**Comment by mattdrayer** [comment]
> @bradenmacdonald Since we can glean `org` from the content ID, should this be included in the index too (along with `content type`), even though we don't technically need it right now?

By "glean" do you mean extract it from the key?  If this is the case be sure to do it via the [opaque keys](https://github.com/openedx/opaque-keys) library vs simply parsing it out of the key itself with a regex/split.

**Comment by bradenmacdonald** [comment]
Our implementation plan is in [this doc](https://docs.google.com/document/d/1nRPj1JtixVBEi9sd7YmZTtNXgJP9R7ffIWlRVzy8QV4/edit).
