### ISSUE TITLE
[Copy/paste] Improve Unit and Component Copy/Paste UX

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#92]
* Fix the spinner animation during paste so that the spinner is vertically centered.
* Fix: close notification button is not readable nor does it match the designs
    * Currently it appears as:
       ![Screenshot 2023-08-15 at 11 46 18 AM](https://github.com/openedx/modular-learning/assets/945577/744f9460-85ea-4529-9736-88275f22687c)
   * Expected design is:
       ![Screenshot 2023-08-15 at 11 48 00 AM](https://github.com/openedx/modular-learning/assets/945577/18f83e39-c80b-45aa-a2c7-fdc33ef932ef)

------ Done already:

* Fixed: on the unit and component pages, multiple menus can be open at the same time:
    - ![image](https://github.com/openedx/edx-platform/assets/3189670/e8188acb-ef80-4b25-b9ce-a73e2c231e0a)

**Comment by jmakowski1123** [comment]
Implement this animation during unit pasting: I have no opinion on which animation is better. I'd just want it to be a consistent experience throughout. We don't have any animation built into the component paste, do we? Or is it just so fast that I'm not seeing it?

Prompt the user to rename the unit after it's pasted? Since we didn't implement this for components, and it's absence doesn't seem to be causing any complaints, I'm inclined to leave it off for now. Users can just as easily rename the unit, and in many cases we may be removing an unnecessary step for them when they want to keep the same title. I suspect that will be a majority use case anyway - authors wanting to reuse evergreen content like introductory material, guidelines and policies, etc.

**Comment by cassiezamparini** [comment]
Looking good @bradenmacdonald 

Some notes:

- This is probably related to "Copying the LibraryContentBlock error", but I thought I'd also mention my experience in case. If I add the Library Content Block to a unit, then copy and paste the unit, I get an error that the unit wasn't pasted. But when I refresh my screen the unit _has_ been pasted, but the Library Content Block has been automatically removed from within the unit. [See screencast.](https://www.loom.com/share/bcd9def9c9924e0b85c92e235553f4e4?sid=0f01d741-ad94-4d99-9668-92a6a1372fc4)
- I'm not sure if "Error: visibility_editor.html" is related to this body of work. But I thought I'd mention it in case. You'll see it in my previous video as well, but [I also had another attempt](https://www.loom.com/share/a088b8e433c24e6e9ac7fe2a3ea5bc24?sid=e3354a72-3c4a-4569-be2c-77cfeee94ff5) in case it was related only to pasting units. That doesn't seem to be the case. But ignore this note, if it doesn't apply. 
- Include "Copy of..." to denote the pasted unit in [Course Outline](https://www.figma.com/file/y2qfzidTxxfYK8ONgyT7KP?node-id=1364:9187&mode=design#529400434) and in [Unit](https://www.figma.com/file/y2qfzidTxxfYK8ONgyT7KP?node-id=660:645&mode=design#529418040). I know you display this quickly in the animation, but you'll see in the design the "Copy of" remains until the user explicitly changes it. This is more the common UX practice, eg. Google docs. Then I don't think we need to prompt the user to immediately rename the unit. We just need some sort of differentiator. @jmakowski1123 Thoughts?
- I see the animation when pasting a unit on the course outline. Happy for you to use the existing animation. I would just keep it consistent (ie. use it when pasting a component too, along with the "pasting" toast messages). 
- Please try centre the pasting spinner within the height of the block.
- I got an error copying and pasting a video component. [See screencast. ](https://www.loom.com/share/77bf9b11e7434017b765b431513d107c?sid=a5a97134-d37d-4157-b5c2-2b64f4474967)

**Comment by bradenmacdonald** [comment]
I tend to agree with @jmakowski1123 that in many cases, authors will be copying from a template course and then pasting the unit into a new course "as is", so if we prepend "Copy of" to the title each time, it just creates unnecessary work for them to remove it. At least that's how I understood her comment above.

**Comment by bradenmacdonald** [comment]
> I'm not sure if "Error: visibility_editor.html" is related to this body of work. But I thought I'd mention it in case.

That's unrelated, and a known issue that 2U is currently investigating with some help from me. Thanks for mentioning it just in case though :)

> I got an error copying and pasting a video component. [See screencast.](https://www.loom.com/share/77bf9b11e7434017b765b431513d107c?sid=a5a97134-d37d-4157-b5c2-2b64f4474967)

Interesting. What kind of video is that? It's one you uploaded to "Files & Uploads" and then made into a Video component? I guess we've mostly been testing with videos hosted on YouTube etc, so that could be why this one isn't working.

**Comment by cassiezamparini** [comment]
> Interesting. What kind of video is that? It's one you uploaded to "Files & Uploads" and then made into a Video component? I guess we've mostly been testing with videos hosted on YouTube etc, so that could be why this one isn't working.
It was just a Loom video I downloaded and then uploaded. 

> I tend to agree with @jmakowski1123 that in many cases, authors will be copying from a template course and then pasting the unit into a new course "as is", so if we prepend "Copy of" to the title each time, it just creates unnecessary work for them to remove it. At least that's how I understood her comment above.
This conversation is ringing a bell! And I totally understand. The design files confused me. In that case, I **_do_** think we need to allow the user to immediately change the name of the pasted item. There needs to be some way to denote the pasted item. Also we'll see how the users respond to this when released anyway.

**Comment by cassiezamparini** [comment]
@bradenmacdonald I like the idea of the animation! Let's explore when we get there.
