### ISSUE TITLE
[Tagging] Automatically add system tags for Language (to library blocks)

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#97]
Same as https://github.com/openedx/modular-learning/issues/79 

"As a content author, I want the system to maintain automatic tags on my **library** content so that I don't have to perform these tasks manually when creating/updating content."

## Blocking work

This should not be implemented until the "library v2 migration" has been largely completed by 2U, because otherwise this work may need to be re-done or altered after that work has been completed.

## Acceptance Criteria

* Whenever a user creates a new XBlock in a content library (v2), the new XBlock should be automatically tagged with a language tag.
* Users can manually override the automatically-set language tag, if the auto-set version is incorrect. Once a user has changed the language tag, it will retain their preferred tag even if the block is later edited.
* For the MVP, the automatic tag set on block creation should be set to the preferred language of the user who created it (either as set in Open edX or as determined from their browser).
* When an operator runs the "update tags" management command with a given "content author user ID" and a list of library or library block IDs, a new Language tag is auto-created for each block [in the specified library(ies)] if one does not already exist.

**Comment by pomegranited** [comment]
@bradenmacdonald CC @jmakowski1123 

> This should not be implemented until the "library v2 migration" has been largely completed by 2U, because otherwise this work may need to be re-done or altered after that work has been completed.

Who/where can we track progress on 2U's library v2 migration?

**Comment by jmakowski1123** [comment]
> @bradenmacdonald CC @jmakowski1123
> 
> > This should not be implemented until the "library v2 migration" has been largely completed by 2U, because otherwise this work may need to be re-done or altered after that work has been completed.
> 
> Who/where can we track progress on 2U's library v2 migration?

There's a slack thread #content-libraries-v2 that's the public space.

**Comment by bradenmacdonald** [comment]
@pomegranited I think that work is far enough along that we can work on this task. Though I also think a lot of the work was already done during an earlier phase of this project?

**Comment by pomegranited** [comment]
@bradenmacdonald  Cool, if libraries v2 is ready, then we are too:  we've already got the models and events ready, just have to add the signal handlers.
